### DISCUSSION TITLE
package extensions for mozilla/pdfjs-dist?

### DISCUSSION THREAD

**Discussion by jcamden** [yarnpkg/berry#2289] [Q&A] [answered]
Greetings! 

I'm a big fan of Yarn 2. Thanks @arcanis et al! Lately, I've been wrestling with mozilla/pdfjs-dist. I've created a [repo that repros the issues](https://github.com/jcamden/pdfjs-yarn-2), and I submitted mozilla/pdf.js#12778. However, they immediately closed the issue because [they don't do Yarn 2](https://github.com/mozilla/pdf.js/issues/12778#issuecomment-751671898). Maybe you guys can help me sort this out:

From what I gather, when used in conjunction with webpack, pdfjs relies on [worker-loader](https://v4.webpack.js.org/loaders/worker-loader/). In fact, they have a "zero-config" wepback entry point which automatically configures work-loader, accessed via `import pdfjsLib from 'pdfjs-dist/webpack';` as per the "Worker loading" section of [the readme for their webpack example](https://github.com/mozilla/pdf.js/tree/master/examples/webpack). As expected, pdfjs cannot compile without the dependency: 
![Screenshot_2020-12-29_17-45-17](https://user-images.githubusercontent.com/5461045/103318845-a5136f80-49fd-11eb-85da-cc7fe6f036e9.png)
This looks like a job for a package extension:
```
packageExtensions:
  pdfjs-dist@^2.6.347:
    dependencies:
      worker-loader: '^2.0.0'
```
(Note that, somewhere in their issues section, I read that pdfjs-dist relies on worker-loader ^2, whereas ^3 will break. Hard to tell without any deps listed in the package.json, but anyway) This is progress:
![Screenshot_2020-12-29_17-51-09](https://user-images.githubusercontent.com/5461045/103319080-7e096d80-49fe-11eb-8337-8bf8c3836198.png)
So worker-loader needs Webpack:
```
packageExtensions:
  pdfjs-dist@^2.6.347:
    dependencies:
      worker-loader: '^2.0.0'
  worker-loader@^2.0.0:
    dependencies:
      webpack: '^5.0.0'
```
When I extend worker-loader's deps with webpack, whether ^4 or ^5, both cases get me here:
![Screenshot_2020-12-29_17-54-05](https://user-images.githubusercontent.com/5461045/103319222-025bf080-49ff-11eb-82d1-62d635e98892.png)
From there, I'm not quite sure what's going on. It is indeed true that "esmodule" is not one of [worker-loader's options](https://v4.webpack.js.org/loaders/worker-loader/#options). I'm not sure why that is getting passed as an option by pdfjs. I've also tried worker-loader ^3 with the same results. Has anyone had any success using pdfjs with webpack in a Yarn 2 repo? Or does anyone have any hints for what next steps I could take? I appreciate it :)

**Comment by merceyz** [comment, marked as answer]
Hello, tested your repro and as the error shows (sort of) they lack an optional(?) peer dependency on `worker-loader@^3`

```yml
packageExtensions:
  'pdfjs-dist@*':
    peerDependencies:
      worker-loader: '^3'
```

> It is indeed true that "esmodule" is not one of worker-loader's options.

It's one of the options for `worker-loader@^3`
