### DISCUSSION TITLE
'yarn node' memory overhead? (disable plugins?)

### DISCUSSION THREAD

**Discussion by jrr** [yarnpkg/berry#2641] [Q&A] [answered]
I'm trying to remove `nodeLinker: node-modules` from a project, and hit a surprising snag when I made the `node` -> `yarn node` switch in my deployed app:

```
Range Error: Array buffer allocation failed (when initializing @yarnpkg/plugin-interactive-tools, defined in /var/task/.yarnrc.yml)
 at new ArrayBuffer (<anonymous>)
 at wrapper (/var/task/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:74:30993)
(...)
```

Looks like it's running out of memory. (This is in AWS Lambda, with the default meager 128mb)

My .yarnrc.yml:
```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
```

Sure enough, removing interactive-tools fixes it.

So, a few questions:
- Is interactive-tools known to be memory-expensive?
- What is interactive-tools doing during normal `yarn node` invocations? (I would expect it to only be active when I run `yarn upgrade-interactive`)
- Is there a way I can conditionally disable the plugin? (I want to keep it in `yarnrc.yml` for development use)
