### DISCUSSION TITLE
How to migrate private scoped packages from .npmrc to .yarnrc.yml?

### DISCUSSION THREAD

**Discussion by Yohanna** [yarnpkg/berry#2756] [Q&A] [answered]
I'm migrating a Yarn v1 project that uses private scoped packages. The project is first setup to create an `.npmrc` file with the following values:

```sh
@<scope_name>:registry:https://private.registry.com/
//private.registry.com//:_password=<base64 encoded authentication token>
//private.registry.com//:username=email@domain.com
//private.registry.com//:email=email@domain.com
//private.registry.com//:always-auth=true
```

I assumed I have to use [npmRegistries](https://yarnpkg.com/configuration/yarnrc#npmRegistries) and [npmScopes](https://yarnpkg.com/configuration/yarnrc#npmScopes) in my configuration like so:

```yml
nodeLinker: node-modules

npmRegistries:
  //private.registry.com:
    npmAlwaysAuth: true
    npmAuthIdent: "email@domain.com:<base64 encoded authentication token>"

npmScopes:
  <scope_name>:
    npmRegistryServer: https://private.registry.com/

yarnPath: .yarn/releases/yarn-berry.cjs
```

But when I run `yarn install` after deleting `node_modules` & `yarn.lock`, I get this error:

```
YN0041: │ @<scope_name>/<package_name>@npm:^3.0.5: Invalid authentication (as an unknown user)
```

How can I migrate `.npmrc` file properly to Yarn v2?

Yarn: v2.4.1
Node.js: v14.16.0

Thank you :)

**Comment by arcanis** [comment, marked as answer]
Can you try base64'ing your whole ident? Cf this similar thread: https://github.com/yarnpkg/berry/issues/316#issuecomment-652712776

If it's this, we probably should help detect the problem.

**Reply by Yohanna** [reply]
Thanks, @arcanis. That fixed the issue!

Maybe we can update the [npmAuthIdent docs](https://yarnpkg.com/configuration/yarnrc#npmAuthIdent) to mention the base64 encoding part?

**Comment by merceyz** [comment]
If you run `yarn set version 3.0.0-rc.1` you should be getting a more detailed error.

> I assumed I have to use npmRegistries and npmScopes in my configuration like so:

You can use just `npmScopes` if you want to

```yml
npmScopes:
  <scope_name>:
    npmRegistryServer: https://private.registry.com/
    npmAlwaysAuth: true
    npmAuthIdent: "email@domain.com:<base64 encoded authentication token>"
```
