### DISCUSSION TITLE
Use binary of dependency

### DISCUSSION THREAD

**Discussion by matzeeable** [yarnpkg/berry#2843] [Q&A] [answered]
Imagine the following workspace structure:

```
- packages/
  - webpack-config/
    - package.json
      name: @my-monorepo/webpack-config
      devDependencies: webpack-cli
  - my-frontend/
    - package.json
      name: @my-monorepo/my-frontend
      devDependencies: @my-monorepo/webpack-config
      scripts:
        - yarn webpack
```

Unfortunately, my frontend package cannot access the `webpack` cli:

```
Usage Error: Couldn't find a script named "dotenv".
```

Is it somehow possible to access the Webpack CLI anyway without adding `webpack-cli` as a dependency to my frontend?

Related: #2825, #2784

**EDIT:** I want to avoid something like `g:webpack` as described here: https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
