### DISCUSSION TITLE
How to use eslint?

### DISCUSSION THREAD

**Discussion by benkeil** [yarnpkg/berry#3119] [Q&A] [answered]
```json
{
  "name": "foobar",
  "private": true,
  "version": "1.0.0",
  "workspaces": [
    "code/**"
  ],
  "scripts": {
    "release": "standard-version",
    "release:minor": "standard-version --release-as minor",
    "release:patch": "standard-version --release-as patch",
    "release:major": "standard-version --release-as major",
    "lint": "eslint"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.4",
    "@commitlint/config-conventional": "^12.1.4",
    "husky": "^7.0.1",
    "prettier": "^2.3.2",
    "standard-version": "^9.3.0",
    "eslint": "^7.30.0"
  }
}
```

Theoretical I want to run eslint separate in every sub package.

```
$ yarn run lint
command not found: eslint
```

my .yarnrc.yml

```yaml
nodeLinker: node-modules

npmScopes:
  trustedshops:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
```

How do I run `eslint`?
