### DISCUSSION TITLE
install always fails without error

### DISCUSSION THREAD

**Discussion by zlk89** [yarnpkg/berry#4399] [Q&A]
I just migrated from yarn v1 to v3.2.0.
But when I run `yarn install` or `yarn workspaces focus --all --production`, it always fails after a few secs during fetch step:

```
root@localhost:~/app# yarn workspaces focus --all --production
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @mui/x-date-pickers@npm:5.0.0-alpha.0 [35807] doesn't provide react-dom (pb7a9d), requested by react-transition-group
➤ YN0060: │ ali-ec2@workspace:. provides react (p41ede) with version 18.0.0, which doesn't satisfy what @mui/lab and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 264ms
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠇ ===============================================================================-
```

node version is v16.14.2
ubuntu version: 18
opt out of zero-install

my .yarnrc.yaml:

```
enableGlobalCache: true

enableMirror: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
```

Note that the same project works well in my windows Linux subsystem (ubuntu 20) with same version of node and yarn.
