### DISCUSSION TITLE
How to properly configure auth

### DISCUSSION THREAD

**Discussion by viceice** [yarnpkg/berry#4882] [Q&A] [answered]
I'm trying to configure auth for a private package which is scoped.

So i've this in `~/.yarnrc.yml`

```yml
npmRegistries:
  //gitea.domain.test/api/packages/org/npm:
    npmAuthToken: token
    npmAlwaysAuth: true
```

and this in repo `.yarnrc.yml`
```yml
nodeLinker: node-modules
defaultSemverRangePrefix: ''

supportedArchitectures:
  os: [linux, win32]
  cpu: [x64]

npmScopes:
  org:
    npmRegistryServer: https://gitea.domain.test/api/packages/org/npm
```

but i still get `Invalid authentication (as an unknown user)`

Do i make something wrong or isn't this a supported scenario?
