### DISCUSSION TITLE
In yarnrc can supportedArchitectures be limited to tuples of cpu/os?

### DISCUSSION THREAD

**Discussion by jeff-wishnie** [yarnpkg/berry#5139] [Q&A]
My dev team uses:
- Windows on x64
- macOS on x64 and arm64
- Linux on x64 

So I set supported architectures as:

```
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - win32
    - macos
```

But this means I get binary esoteric packages I don't need like `esbuild-windows-arm64` 

It's not the end of the world to cache these unused permutations, but is there a way to specify specific tuples e.g.

```
supportedArchiitectures:
  - cpu:
       - x64
    os:
      - win32
      - macos
      - linux
  - cpu:
      - arm64
    os:
      - macos
 ```

???
