### DISCUSSION TITLE
How to repair a store after manual changes with hardlinks-global?

### DISCUSSION THREAD

**Discussion by donferi** [yarnpkg/berry#5188] [Q&A]
How can I repair the store after modifying it?

Some context: I'm using the following `.yarnrc.yml` in two projects, project A and project B, on macOS.

Running yarn `3.3.1`
```yml
nodeLinker: node-modules
compressionLevel: 0
enableGlobalCache: true
nmMode: hardlinks-global
```

If I install let's say `is-even` in project A and project B, they are hard-linked as expected. If I then I go to project `A` and modify `node_modules/is-even/package.json` I can go to project `B` and see the changes there too.

My question is, how can I restore this modification? I tried `yarn install`, `yarn install --check-cache`, `yarn install --immutable` but nothing errors out or reverts the change. The only thing that worked for me was to `rm -rf node_modules` in either project and run `yarn install` again, but this seems like not the right way to go about it. What am I missing?
