### DISCUSSION TITLE
How to configure registry URL on a per package basis?

### DISCUSSION THREAD

**Discussion by viglucci** [yarnpkg/berry#5502] [Q&A]
Is it possible to configure a registry on a per-package basis?

We are using AWS CodeArtifact to host several packages and the scope remains the same for the package, however that same scope needs to be resolvable from a different registry for different packages. 

In the case of AWS CodeArtifact, a package "repository" informs the registry URL, and the AWS CodeArtifact repository is unopinionated about the NPM scopes that the packages published there use.

To change the registry on a per scope basis we currently can set the following configuration in `yarnrc.yml`:

```yml
npmRegistries:
  "//abc-123.d.codeartifact.us-west-2.amazonaws.com/npm/my-package/":
    npmAlwaysAuth: true
    npmAuthToken: ${AWS_NPM_AUTH_TOKEN}

npmScopes:
  my-scope:
    npmRegistryServer: //abc-123.d.codeartifact.us-west-2.amazonaws.com/npm/my-package/
```

It would be hugely useful to be able to set configuration so that specific packages resolve to specific registries:

```yml
npmRegistries:
  "//abc-123.d.codeartifact.us-west-2.amazonaws.com/npm/my-package/":
    npmAlwaysAuth: true
    npmAuthToken: ${AWS_NPM_AUTH_TOKEN}
  "//abc-456.d.codeartifact.us-west-2.amazonaws.com/npm/my-package/":
    npmAlwaysAuth: true
    npmAuthToken: ${AWS_NPM_AUTH_TOKEN}

npmPackages:
  "my-scope/my-package-2":
    npmRegistryServer: //abc-456.d.codeartifact.us-west-2.amazonaws.com/npm/my-package/
```

Is this possible?
