### ISSUE TITLE
[Bug] Compatibility issues

### ISSUE THREAD

**Issue by kirill-konshin** [yarnpkg/berry#1012]
- [x] I'd be willing to implement a fix

**Describe the bug**

Possible candidates for compat plugin...

Everything is quite outdated... so I had to add following to `.yarnrc.yml`:

```yml
packageExtensions:
  "@testing-library/react@*":
     dependencies:
       react: "16.8.6"
  "@testing-library/react-hooks@*":
     dependencies:
       react: "16.8.6"
  react-dom@*:
     dependencies:
       react: "16.8.6"
  react-test-renderer@*:
     dependencies:
       react: "16.8.6"
  enzyme-adapter-react-16@*:
     dependencies:
       react: "16.8.6"
```

Versions:

- `react-dom`: 16.8.6
- `@testing-library/react`: 9.4.0
- `@testing-library/react-hooks`: 3.2.1
- `enzyme-adapter-react-16`: 1.15.1
