### ISSUE TITLE
[Bug] Invalid authentication (as an unknown user) with Azure Devops Artifacts

### ISSUE THREAD

**Issue by IT-CASADO** [yarnpkg/berry#1442]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I'm desperately trying to use Yarn 2 with a private repository from Azure Devops Artifacts.
But I'm always getting an error "Invalid authentication (as an anonymous user)"

**To Reproduce**

My package.json 

```
{
	"name": "yarn2",
	"version": "1.0.0",
	"main": "index.js",
	"author": "Daniel Casado",
	"license": "MIT",
	"devDependencies": {
		"@casado/casado.editor-config": "^1.0.0"
	}
}
```

and .yamlrc.yml

```
npmScopes:
  "casado":
    npmAlwaysAuth: true
    npmRegistryServer: "https://pkgs.dev.azure.com/it-casado/apps/_packaging/casado/npm/registry"
    npmAuthToken: "NGZ4aWVvc2I0Zm1odnhpZjdjZ3U2bndnbHN0aXM2N3l0c2lsNGtpdmU1N2tyN2p6YnR5cQ=="

yarnPath: ".yarn/releases/yarn-berry.js"
```

_Note: The provided token is a read-only token to a testing repository!_

I also tryied:

```
npmScopes:
  "casado":
    npmAlwaysAuth: true
    npmRegistryServer: "https://pkgs.dev.azure.com/it-casado/apps/_packaging/casado/npm/registry"
    npmAuthIdent: "it-casado:NGZ4aWVvc2I0Zm1odnhpZjdjZ3U2bndnbHN0aXM2N3l0c2lsNGtpdmU1N2tyN2p6YnR5cQ=="

yarnPath: ".yarn/releases/yarn-berry.js"
```

This token is working under NPM  abd Yarn V1 (with .npmrc).

```
always-auth=true
@casado:registry=https://pkgs.dev.azure.com/it-casado/apps/_packaging/casado/npm/registry/

//pkgs.dev.azure.com/it-casado/apps/_packaging/casado/npm/registry/:username=it-casado
//pkgs.dev.azure.com/it-casado/apps/_packaging/casado/npm/registry/:_password=NGZ4aWVvc2I0Zm1odnhpZjdjZ3U2bndnbHN0aXM2N3l0c2lsNGtpdmU1N2tyN2p6YnR5cQ==

# token: 4fxieosb4fmhvxif7cgu6nwglstis67ytsil4kive57kr7jzbtyq
# tokenBase64: NGZ4aWVvc2I0Zm1odnhpZjdjZ3U2bndnbHN0aXM2N3l0c2lsNGtpdmU1N2tyN2p6YnR5cQ==
```

**Environment if relevant (please complete the following information):**

 - OS: [Windows.]
 - Node version [12.17.0]
 - Yarn version [2.0.0-rc.33]

**See also**
[Azure Artifacts - Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows#linux-or-mac)
