### ISSUE TITLE
[Bug] npm login to a private registry only works with manual fix

### ISSUE THREAD

**Issue by kamikazePT** [yarnpkg/berry#1484]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I have a private Nexus registry, which needs the flag "always-auth" to be true to work, otherwise yarn gives me unauthorized when getting packages.

**To Reproduce**

- add `npmAlwaysAuth: true` on .yarnrc.yml and `npmRegistryServer: <my-registry-url>` on the project's yarnrc.yml file
- execute `yarn npm login` successfully
- yarn install fails and assumes I'm using a non-authenticated user (anonymous user)

**Workaround**

If I go to the .yarnrc.yml file at user level (instead of the one at the project) on the npmRegistries entry, adding the npmAlwaysAuth as true on the desired registry fixes the `yarn install ` command

user .yarnrc.yml
```
npmRegistries:
  "<my-registry-url>":
    npmAuthToken: <generated-token>
    npmAlwaysAuth: true -> this needs to be added manually even if npmAlwaysAuth is true on project .yarnrc.yml
```

**Desired Behaviour**

When executing `yarn install`, the npmAlwaysAuth flag on the project specific .yarnrc.yml should override the default that is generated on user level .yarnrc.yml at the npmRegistries entry created
