### ISSUE TITLE
[Bug] Canary builds including commit hash are not resolved correctly

### ISSUE THREAD

**Issue by ChiefORZ** [yarnpkg/berry#1507]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When releasing canary builds with lerna - the convention is relasing it with `x.y.z-canary.n+commit_hash`, which is semver compatible and will always result as `x.y.z-canary.n` on the registry.
When using `yarn up foo@canary` it throws following Error: `Error: foo@npm:^0.5.1-canary.155+2c22234: Expected the resolution to have been successful - package not found`.

**To Reproduce**

The yarn.lock describing the problem:

```
"my-package@workspace:packages/my-package":
  version: 0.0.0-use.local
  resolution: "my-package@workspace:packages/my-package"
  dependencies:
    "bar": canary
    "foo": canary
  languageName: unknown
  linkType: soft

"foo@npm:^0.5.1-canary.155+2c22234, foo@npm:canary":
  version: 0.5.1-canary.155
  resolution: "foo@npm:0.5.1-canary.155"
  checksum: 074ee04c95baf2ba6444f3d29ce085ebc47bab855d9d371db90de5dd17b88f5bcbf3592c25545008697f168f4e17bd20b47353c4c71da05465308ce1c45dba87
  languageName: node
  linkType: hard

"bar@npm:canary":
  version: 2.2.7-canary.117
  resolution: "bar@npm:2.2.7-canary.117"
  dependencies:
    "foo": ^0.5.1-canary.155+2c22234
  checksum: 0c8b6460848001803bd80d8bf02255bb7019404f1329f466b6fa4e59722ac0b0af8994b76f3e62805864f63ec52ecb9b771d3b07fd960219f2a8860903601910
  languageName: node
  linkType: hard
```

<details>
  <summary>Reproduction</summary>

  ```js repro
  const installPromise = packageJsonAndInstall({
  dependencies: {
  [`@polka/url`]: `next`,
  [`polka`]: `next`,
  },
  });

  await expect(installPromise)
  .resolves.toBeTruthy();

  const updatePromise = yarn(`up`, `@polka/*@next`);

  await expect(updatePromise)
  .resolves.toBeTruthy();
  ```

---
</details>

**Comment by ChiefORZ** [comment]
Side information - this behaviour is only occurring on the branch https://github.com/yarnpkg/berry/pull/1504 (`yarn set version from sources --branch 1504`).
We just tried it on the latest yarn release, and there it seems to work normally. (`yarn-2.0.0-rc.36.js`)

**Comment by ChiefORZ** [comment]
The error is still occurring in the latest release - yarn v2.1.1

For anyone else stumbling upon this error - we are temporarily stripping out all commit-hashes from the `yarn.lock` before running the upgrade. 
```bash
sed -E 's/\+([a-z0-9]*)//g' yarn.lock
yarn up foo@canary
```

As it seems, yarn is searching the string `foo@npm:^0.5.1-canary.155+2c22234` from the yarn.lock in the cache folder - but there is only a `foo-npm-0.5.1-canary.155-9a2936330d-43a2f6a3a4.zip` file.

**Comment by ChiefORZ** [comment]
I came acros the problem once more right now, upgrading all storybook repositories in our project: `yarn up @polka/*@next`.

While writing the sherlock scripts i came acros following infos:

## Following example will run without errors

```js repro
  const installPromise = packageJsonAndInstall({
    dependencies: {
      [`@polka/url`]: `next`,
    },
  });

  await expect(installPromise)
    .resolves.toBeTruthy();

  const updatePromise = yarn(`up`, `@polka/*@next`);

  await expect(updatePromise)
    .resolves.toBeTruthy();
```

because the yarn.lock looks like this:

```
"@polka/url@npm:next":
  version: 1.0.0-next.11
  resolution: "@polka/url@npm:1.0.0-next.11"
  checksum: 268a83f4e1097baf0067e183b7682a00b647c6c30113a92b98c80cd719fc689a45d28c16257ffc817f5ffd4894fc52157957c39aaac329cdd12c82a10f6d61f7
  languageName: node
  linkType: hard
```

## But in this example it will fail

```js repro
  const installPromise = packageJsonAndInstall({
    dependencies: {
      [`@polka/url`]: `next`,
      [`polka`]: `next`,
    },
  });

  await expect(installPromise)
    .resolves.toBeTruthy();

  const updatePromise = yarn(`up`, `@polka/*@next`);

  await expect(updatePromise)
    .resolves.toBeTruthy();
```

because the yarn.lock looks like this:

```
"@polka/url@npm:^1.0.0-next.11, @polka/url@npm:next":
  version: 1.0.0-next.11
  resolution: "@polka/url@npm:1.0.0-next.11"
  checksum: 268a83f4e1097baf0067e183b7682a00b647c6c30113a92b98c80cd719fc689a45d28c16257ffc817f5ffd4894fc52157957c39aaac329cdd12c82a10f6d61f7
  languageName: node
  linkType: hard

"polka@npm:next":
  version: 1.0.0-next.11
  resolution: "polka@npm:1.0.0-next.11"
  dependencies:
    "@polka/url": ^1.0.0-next.11
    trouter: ^3.1.0
  checksum: 03d7e34a55cc54714fc9ec3428874a1b8d7044e02ecd3f33acd6d056b4c6188ac30f1dd18cf4afae372969e7f5c6ac8642c064c6efbb906de92f76ca8f268470
  languageName: node
  linkType: hard
```
