### ISSUE TITLE
[Feature] noProxy configuration option support

### ISSUE THREAD

**Issue by Sshnyari** [yarnpkg/berry#1530]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

When working behind a proxy, depending on its configuration, some urls are not reachable and we shouldn't use the proxy to access them. I am in such an environment right now, where the npm registry should be accessed via the proxy and the company's shouldn't.

**Describe the solution you'd like**

adding a config variable noProxy in the .yarnrc.yml file that behaves like the NO_PROXY environment variable would do the job. for example:
httpProxy: someproxy.com:0000
noProxy: localhost,127.0.0.1,someinternalurl.thatshouldntusetheproxy.com

**Describe the drawbacks of your solution**

Since I am not a proxy expert, I don't know of any existing drawbacks of using the provided "system proxy".

**Describe alternatives you've considered**

no alternatives found. this is actually a blocking issue to move to yarn v2

**Additional context**

It already works with yarn v1 by setting the corresponding environment variables

**Comment by Sshnyari** [comment]
I digged a little into the issue. neither [got](https://github.com/sindresorhus/got) nor [tunnel](https://github.com/koichik/node-tunnel) have the support for no_proxy natively.
I see two options;
- replace tunnel with [global-agent](https://github.com/gajus/global-agent), which doesn't support legacy versions of node
- ignore the httpProxy and httpsProxy settings from configuration and use something like [proxy-from-env](https://github.com/Rob--W/proxy-from-env) to decide whether or not to use the proxy

I wanted to make a PR, but I don't know the implications of both options.

**Comment by erict-square** [comment]
As far as I'm aware, there's still no noproxy support in yarn. https://github.com/yarnpkg/berry/pull/2156 implements the http-proxy and https-proxy functionality, but the option to skip proxy for certain domains is still not possible atm.

We have a setup where our Artifactory instance (to serve NPM modules) is on an on-prem setup that doesn't require proxy. However, our Artifactory returns a CloudFront CDN redirect that would need to use proxy. This introduces a scenario where we need to conditionally use proxy depending on the domain. AFAIK, noproxy also works in `npm` and many other build tools and it feels like `yarn` should be able to do that too! Is there a reason why `yarn` doesn't support noproxy now?

Would love to get your input, @arcanis! I'm happy to help contribute as well

**Comment by pustekuchen91** [comment]
This issue should be reopened. Its not possible to configure something like this 

- Use a proxy for all, expect domain X

Examples: 
```
networkSettings:
  "*.mydomain.de":
    httpProxy: ""
    httpsProxy: ""
  "*":
    httpProxy: "http://proxy.mydomain.de:3128"
    httpsProxy: "http://proxy.mydomain.de:3128"

```
or 

```
httpProxy: "http://proxy.mydomain.de:3128"
httpsProxy: "http://proxy.mydomain.de:3128"

networkSettings:
  "*.mydomain.de":
    httpProxy: ""
    httpsProxy: ""
```

This aint work, because some packages seems to use a IP Adress, so install fails with 
`➤ YN0001: │ RequestError: connect ETIMEDOUT 104.16.26.35:443`

`networkSettings` seems to be valid only for hostnames and have no IP-Adresse support, when using `*`
