### ISSUE TITLE
[Bug] YN0041: Invalid authentication after logging in with `yarn npm login`

### ISSUE THREAD

**Issue by justjake** [yarnpkg/berry#1641]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I attempted to publish my package via `yarn npm login` and `yarn npm publish`, but yarn failed with an unexpected error

**To Reproduce**

Using `yarn` from sources in this repo: https://github.com/justjake/quickjs-emscripten

1. Clone https://github.com/justjake/quickjs-emscripten
1. Try to `yarn npm login`
1. Try to `yarn npm publish` 

**Screenshots**

![image](https://user-images.githubusercontent.com/296279/88773758-61a79300-d137-11ea-9ab7-d6c7327ce6b2.png)

**Environment if relevant (please complete the following information):**

 - OS: macOS 10.14.6 (18G103)
 - Node version: v10.21.0
 - Yarn version: 2.1.1-git.20200720.906e9472

**Comment by justjake** [comment]
Tried `yarn npm login --help`:

![image](https://user-images.githubusercontent.com/296279/88775093-260dc880-d139-11ea-82f4-04adbc259b33.png)

Tried `yarn npm login --publish`; did not change the result of `yarn npm publish`

**Comment by arcanis** [comment]
That's curious - what do you get with `yarn npm whoami`? 🤔

**Comment by justjake** [comment]
@arcanis it returns `jitl`, as expected

**Comment by arcanis** [comment]
Hm. Any chance it was a temporary registry issue? I published packages this afternoon and it seemed to work, and the message you reported indicate the registry returned a 401 or 403

**Comment by justjake** [comment]
@arcanis I looked at my `~/.yarnrn.yml`, is this syupposed to be `https://registry.yarnpkg.com`? Or should it be configured for something with www.npmjs.com in the URL.

**Comment by justjake** [comment]
I just tried again after doing `yarn set version from sources`, same error

**Comment by arcanis** [comment]
Yep, both registries are the same (the Yarn endpoint is a cname to npm). I'll try tomorrow to publish your package under a test name to see if I can repro. Are you using OTP?

**Comment by justjake** [comment]
No, I am not.

After running `yarn npm logout`, attempts to log in now fail as so:
![image](https://user-images.githubusercontent.com/296279/88864180-7462ac00-d1b9-11ea-9463-61633012d4c7.png)

I believe this is because this is the state of `~/.yarnrc.yml` after `yarn npm logout`
![image](https://user-images.githubusercontent.com/296279/88864215-86dce580-d1b9-11ea-8aae-e19e6e7800ba.png)

**Comment by justjake** [comment]
What does the `--publish` flag mean for `yarn npm login`?

**Comment by justjake** [comment]
created issue https://github.com/yarnpkg/berry/issues/1663 to track the `yarn npm login; yarn npm login` bug

**Comment by inomdzhon** [comment]
I have same issue =(

`yarn npm login` successfully logged in, but `yarn npm publish` is `Invalid authentication (as undefined)`

Here my `.yarnrc.yml`
```
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.2.0.cjs

npmRegistryServer: "https://jfrog.space307.tech/api/npm/space307-frontend-local/"

npmPublishRegistry: "https://jfrog.space307.tech/api/npm/space307-frontend-local/"
```

**Comment by arcanis** [comment]
> Anyway log by yarn is very uninformative – `Invalid authentication (as undefined)` say me nothing about real issue =(

Yep, @paul-soporan investigated a bit and it seems that any 403 (which is what the server answers) are reported as `Invalid authentication` - plus a missing option in one of the calls that caused the `as undefined`. We'll fix both issues!

**Comment by paul-soporan** [comment]
Thanks for the reminder @arcanis! I've almost forgotten about this. Will open a PR later today. 👍

**Comment by paul-soporan** [comment]
Just opened #1809. You can try it out by doing `yarn set version from sources --branch 1809` and report back what the actual error message is. If it's confirmed that the remaining problems aren't on our side, we can close this issue.

**Comment by merceyz** [comment]
Due to the lack of feedback i'll close this under the assumption that what is actually happening is that you're trying to publish an already existing version, which V2.3 will show better error messages for thanks to https://github.com/yarnpkg/berry/pull/1809

**Comment by inomdzhon** [comment]
Oh, sorry :(
I forget for check, because I downgraded to yarn v1

I checked fix in my branch with yarn v2 and saw next errors

If I try publish without auth
```
➤ YN0033: No authentication configured for request
➤ YN0000: Failed with errors in 24s 296ms
```

If I try publish exist version
```
➤ YN0035: forbidden
➤ YN0000: Failed with errors in 1s 233ms
```

Looks good than before 👍

**Comment by wojtekmaj** [comment]
I'm getting reports from multiple colleagues working in multiple projects that they are unable to log in using `yarn npm login`, using Yarn 2.4 and 3.0. 

The only workaround that seems to be working is adding this in your command line configuration file (.bashrc or .zshrc, depending on your setup):
```
export YARN_NPM_AUTH_TOKEN=your_github_personal_access_token
```
but that works only if you need one auth token. That's a huge bummer.

How can I help you resolving this, and how can I help my colleagues?

**Comment by dgoriunov** [comment]
I am having same problem after using `yarn npm login` and trying to intall dependencies i am getting error: 

```
Invalid authentication
```

as a temporary solution i am using for single token:

```
export YARN_NPM_AUTH_TOKEN=your_github_personal_access_token
```

**Comment by zakzak1978** [comment]
I am also having the same issue.  I was also able to successfully login.  Even after successful login, I see the below error.

UnhandledPromiseRejectionWarning: Error: rxjs@npm:6.6.2: Invalid authentication (as an anonymous user)

**Comment by wojtekmaj** [comment]
I think I have discovered something that can push this forward.

In your GLOBAL `.yarnrc.yml`, you will have your tokens stored. That was my situation:

```yml
npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: SOME_GITHUB_TOKEN_HERE
  "https://registry.yarnpkg.com":
    npmAuthToken: NPM_PUBLISH_TOKEN_HERE

npmScopes:
  acmeinc:
    npmAuthToken: ACMEINC_GITHUB_TOKEN_HERE
```

it looks like `npmRegistries["https://npm.pkg.github.com"].npmAuthToken` took priority over `npmScopes.acmeinc.npmAuthToken`. 
* Removing `npmRegistries["https://npm.pkg.github.com"].npmAuthToken` did not resolve the issue.
* Copying `npmScopes.acmeinc.npmAuthToken` value to `npmRegistries["https://npm.pkg.github.com"].npmAuthToken` resolved the issue. 

I'm still not sure, however, why is that and how to resolve this without manually fiddling with configs.

**Comment by rosanzheng** [comment]
I just had quite a hard time with the authentication part with `Yarn 3.1.0`, but I found the solution to it and hope I can save someone else from the struggles I've been having:

**Problem:**
My requirements were to publish one repository `@organization/test1` into the GitHub NPM registry. But I was not able to install this package from another repository lying within the same organization, because I defined my `.yarnrc.yml` wrongly.
Therefore, I received 404 errors and 401 errors when trying to install it.

**Solution:**
Here's what worked for me regarding the `.yarnrc.yml` file:

```
npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  <Your scope (case sensitive!)>:
    npmAlwaysAuth: true (optional I think)
    npmAuthToken: <Your Personal Access Token>
    npmRegistryServer: <URL to where your package is hosted, in our case it was https://npm.pkg.github.com>
```
