### ISSUE TITLE
[Feature] Loading environment variables from a file for yarnrc.yml

### ISSUE THREAD

**Issue by julienfouilhe** [yarnpkg/berry#1801]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

I'm trying to migrate one of my company's projects to yarn2. One of the things I'm having 'trouble' with is migrating our private registry.

I currently have this in my yarnrc.yml file.

```yaml
npmScopes:
  company:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_PRIVATE_REGISTRY_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"
```

The problem with this is, while it's perfect for docker or CI environments, it' a little bit less ideal for every day development.
All the developers working on the project need to set this environment variable in their shell configuration.

**Describe the solution you'd like**

- Have a global yarnrc file where we could specify scopes tokens, so that it is automatically available in all of my projects.
- Have a way to extend yarnrc.yml files. That way we could specify the scope in a different file, that wouldn't be added to our VCS. It could also be reused by multiple projects.
- Have yarnrc.yml load a dotenv file.

**Describe the drawbacks of your solution**

N/A

**Describe alternatives you've considered**

Adding the env variables in my shell configuration.

**Additional context**

N/A

**Comment by arcanis** [comment]
What about using the following?

```yml
npmScopes:
  company:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_PRIVATE_REGISTRY_TOKEN:-}
    npmRegistryServer: "https://npm.pkg.github.com"
```

Note the `:-`. With this, the value will default to an empty string. They won't be able to publish, but Yarn won't report an error if missing.

**Comment by julienfouilhe** [comment]
Unfortunately, my problem is not with publishing to the private registry, but rather installing dependencies from it.

My project has '@company/name' dependencies, and you need the scope as well as the token to be defined whenever you yarn install.

Also, the problem is not with the token not being defined, the problem is with where you can define such token. Right now you either need to do `env AUTH_TOKEN=mytoken yarn install` or add it to global file loaded by the shell...

I would like to be able to define the token in another file inside my project, that I can add to my `.gitignore`. Every member of my team will have to create the same file, but I think it's better than having to define the variable in a .bashrc or whatever, and months later wonder where you put it...

**Comment by merceyz** [comment]
> Have a global yarnrc file where we could specify scopes tokens, so that it is automatically available in all of my projects.

We already have that, you can set those configs in `~/.yarnrc.yml`

**Comment by yarnbot** [comment]
Hi! 👋

It seems like this issue as been marked as probably resolved, or missing important information blocking its progression. As a result, it'll be closed in a few days unless a maintainer explicitly vouches for it.

**Comment by merceyz** [comment]
Closing as we have a way to set the config globally

**Comment by hmnd** [comment]
> We already have that, you can set those configs in `~/.yarnrc.yml`

@merceyz How would I define an `npmScope` in both the global `yarnrc.yml` and the in-project one and have the global config override the in-project one? I would not consider this issue resolved if that's not possible.
In a project with CI, I want to be able to specify the `npmAuthToken` as an environment variable for CI purposes while not having to manually export the variable or define it in `bashrc` for local development.

**Comment by HeatherFlux** [comment]
I'm jumping back into this for a similar problem. 

I would like to be able to get my auth token on the fly for the devs since we don't currently allow long lived tokens to our remote repositories.

Either through the yarnrc.yml itself
`npmAuthToken: $(aws codeartifact get-authorization-token --domain <some-domain> --domain-owner <1234> --query authorizationToken --output text)`

or through a preinstall script in the package.json that can run before yarn attempts to phone out to our remote repo.

**Comment by lynxtaa** [comment]
I think I've got it to work by using `npmScopes` field in a local `.yarnrc.yml` and a `npmRegistries` field with a token in a `.yarnrc.yml` in a home directory.

A `.yarnrc.yml` file which is committed to the repository:
```yml
npmScopes:
  my-scope:
    npmPublishRegistry: 'https://example.com/npm/'
    npmRegistryServer: 'https://example.com/npm/'
```

And a `~/.yarnrc.yml` file:
```yml
npmRegistries:
  https://example.com/npm/:
    npmAuthToken: <your token>
```

You could setup it by using a simple js script:
```js
```
