### ISSUE TITLE
[Bug] patch-commit is not creating patch file

### ISSUE THREAD

**Issue by darkowic** [yarnpkg/berry#1805]
- [ ] I'd be willing to implement a fix

**Describe the bug**

The [plugin-patch](https://github.com/yarnpkg/berry/blob/master/packages/plugin-patch/README.md) instruction doesn't work as described in its readme.

**To Reproduce**

Follow the `plugin-patch` instruction and try to patch any package. Command `yarn patch-commit /tmp/xfs-592d5fe8` won't create any `.patch` directory nor the patch file.

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]: Linux
 - Node version [e.g. 8.15.0, 10.15.1, ...]: v14.4.0
 - Yarn version [e.g. 2.0.0-rc1, ...]: 2.2.2

**Additional context**

yarn config:
```yml
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
```
