### ISSUE TITLE
[Feature] flag to make peer dependency warnings errors

### ISSUE THREAD

**Issue by bgotink** [yarnpkg/berry#1849]
- [x] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

"X doesn't provide Y" and "X provides Y with version A which doesn't satisfy B requested by Z" are useful warnings. In repositories that are free of these warnings, having one pop up when you change a dependency is hard to miss so it's quite easy to keep the repository warning-free.
However, once these warnings have been present for a while, new ones are invisible when included in the existing ones.

While a missing or wrong peer dependency doesn't always lead to errors, sometimes they do lead to problems.
At our organisation we've got dozens of repositories, maintained by different teams. Not all of those are great at keeping that warning count at zero. Lately I've been getting more and more bugtickets / slack messages about problems where the solution was "see that warning yarn prints? fix that and your problem goes away".

**Describe the solution you'd like**

An option in yarn to make these warnings errors instead, enforcing all devs on the project to keep the warning count at zero.

Enabling this option would implie all of these all need to be fixed either by adding the correct version or by adding a package extension to make the peer dependency optional / change the version.

**Describe the drawbacks of your solution**

It's yet another configuration property.

**Describe alternatives you've considered**

- This could be enforced via a hook instead. That feels like overkill though.
- Teach all developers at my org to take these warnings seriously. Suppose I'd get that message through to everyone, that'd fix the problem for a little while. It'd take a surprisingly short time to run into the same problem again due to developer turnover, new external parties getting involved etc.

**Comment by arcanis** [comment]
I think this would tie nicely into a slightly different feature I have in mind: log filtering. The idea would be to declare in the yarnrc something like this:

```yaml
logFilters:
  - "Package X didn't [...]": discard    # Would completely hide this specific message
  - YN0013: discard                      # Hide all the "Package not in cache" messages
  - YN0002: error                        # All missing peers are errors
```
