### ISSUE TITLE
[Bug] Invalid authentication (as an unknown user)

### ISSUE THREAD

**Issue by Kizmar** [yarnpkg/berry#1874]
**Describe the bug**

I'm working on an npm package project that I'm publishing to an ADO Artifact feed. I had my `.yarnrc.yml` working based on issue #316. I've been able to `yarn npm publish` with success for a couple days.

Yesterday I published a few times, then a few minutes later I tried to publish again and started getting the "Invalid authentication (as an unknown user)" error while running the `yarn npm publish` command. I did not make a change to the `.yarnrc.yml` file since I got it working. I've tried refreshing the PAT in ADO and recreating the base64 string `<org_name>:<PAT>`, but it didn't fix the issue.

I'm not sure how to troubleshoot this. I also tried using my actual user name in the `npmAuthIdent` base64 string (`<user_name>:<PAT>`), which didn't work either. I don't know if something was cached and expired causing this - or what that could even be? I'm able to log in and view the ADO feed just fine.

**To Reproduce**

The `.yarnrc.yml` file looks like this:
```
enableTelemetry: false
nodeLinker: node-modules
npmPublishRegistry: "https://pkgs.dev.azure.com/<org_name>/_packaging/<feed_name>/npm/registry/"
npmRegistryServer: "https://pkgs.dev.azure.com/<org_name>/_packaging/<feed_name>/npm/registry/"
npmPublishAccess: restricted
npmAlwaysAuth: true
npmAuthIdent: base64(<org_name>:<PAT>)

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
```

**Environment:**

 - OS: Windows 10 (current build)
 - Node version 12.18.4
 - Yarn version 2.2.2
