### ISSUE TITLE
[Bug] setting npmRegistryServer to http url will cause yarn to throw error

### ISSUE THREAD

**Issue by Aqours** [yarnpkg/berry#2084]
- [ ] I'd be willing to implement a fix

**Describe the bug**

yarn install will throw error(`GotError: Protocol "https:" not supported. Expected "http:"`) if I set yarnrc.npmRegistryServer to a http url event if I set yarnrc.unsafeHttpWhitelist

**To Reproduce**
<details>
  <summary>Reproduction</summary>

.yarnrc.yml

```yml
# registry.npm.example.co is a private registry, and only support http protocol
defaultSemverRangePrefix: ""
npmRegistryServer: "http://registry.npm.example.co"
unsafeHttpWhitelist:
  - "registry.npm.example.co"
```

partial package.json
```json
{
  "dependencies": {
    "@private-scope/utils": "1.0.111",
    "webworkify": "1.5.0"
  },
}
```
run global yarn to install deps
```shell
yarn install
```

</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/8586286/98231617-9aa59e00-1f97-11eb-8e9a-aa135ddc0471.png)

**Environment if relevant (please complete the following information):**

 - OS: [Windows 10]
 - Node version [12.16.2]
 - Yarn version [2.0.0-rc.27]

**Additional context**
