### ISSUE TITLE
[Bug?] `logFilters` doesn't work with resolution warnings

### ISSUE THREAD

**Issue by borekb** [yarnpkg/berry#2204]
The resolution step produces this warning in our case:

> ➤ YN0060: │ @company/my-package@workspace:my-package provides graphql (pc69a0) with version 14.7.0, which doesn't satisfy what @graphql-codegen/typescript-operations and some of its descendants request

I tried silencing it via `logFilters` but no success:

```
logFilters:
  - text: "satisfy what"
    level: discard
```

(I tried several strings like `"provides graphql"` or `"with version 14.7.0"`, no luck either.)

Should `logFilters` be supported for resolution warnings? I'm not sure if this is a bug or expected behavior.

**Comment by arcanis** [comment]
`logFilter`'s `text` predicate is exact match - `satisfy what` would be partial match. Use `code: YN0060` instead.

**Comment by borekb** [comment]
I can't use `code: YN0060` as I don't want to filter out all YN0060 errors.

I'm trying a full string match but it doesn't seem to work either:

```
logFilters:
  - text: "@company/my-package@workspace:my-package provides graphql (pc69a0) with version 14.7.0, which doesn't satisfy what @graphql-codegen/typescript-operations and some of its descendants request"
    level: discard
```

**Comment by zeorin** [comment]
After some experimentation, I figured out that I needed to omit the `(pXXXXX)` using a glob star, e.g.:

```yaml
logFilters:
  - pattern: react is listed by your project with version *, which doesn't satisfy what @tinymce/tinymce-react and other dependencies request
    level: discard
  - pattern: react-dom is listed by your project with version *, which doesn't satisfy what @tinymce/tinymce-react and other dependencies request
    level: discard
  - text: Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
    level: discard
```
