### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by valdestron** [yarnpkg/berry#2367]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When debugging workspace folders/services that is dependent from`packageExtensions` hack getting error 
`SyntaxError: Cannot use import statement outside a module`

**To Reproduce**

1. use yarn v2 (berry) pnp
2. setup base tsconfig, and then tsconfig per folder
root tsconfig.base.json
```json
{
  "compilerOptions": {
    "pretty": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "target": "esnext",
    "lib": ["esnext", "esnext.asynciterable"],
    "moduleResolution": "node",
    "declaration": true,
    "inlineSourceMap": true,
		"inlineSources": true,
		"importHelpers": true,
		"downlevelIteration": false,
		"alwaysStrict": true,
		"strict": true,
		"strictNullChecks": true,
		"strictFunctionTypes": true,
		"strictBindCallApply": true,
		"strictPropertyInitialization": true,
    "noStrictGenericChecks": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
		"noImplicitThis": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		/* Report error when not all code paths in function return a value. */
    "noImplicitReturns": true,
		/* Report errors for fallthrough cases in switch statement. */
    "noFallthroughCasesInSwitch": false,
    /* Resolve 'keyof' to string valued property names only (no numbers or symbols). */
    "keyofStringsOnly": true,
    /* Do not report errors on unreachable code */
    "allowUnreachableCode": true,
    /* Do not report errors on unused labels. */
    "allowUnusedLabels": false,
    "useDefineForClassFields": false,
    "baseUrl": ".",
		"allowSyntheticDefaultImports": true,
		/* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "esModuleInterop": true,
		"allowUmdGlobalAccess": true,
    "experimentalDecorators": true,
		/* Enables experimental support for emitting type metadata for decorators. */
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
  }
}
```
tsconfg.json in workspace folder
```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "rootDir": "src",
    "outDir": "dist",
    "paths": {
      "*": ["*"]
    },
    "experimentalDecorators": true
  },
  "include": [
    "./src/**/*"
  ],
  "exclude" : ["./src/**/*.spec.ts", "./src/**/*.test.ts"],
}
```
3. setup debugger configuration for the workspace folder
```json
    {
        "type": "pwa-node",
        "request": "launch",
        "name": "svc: workflows",
        "runtimeArgs": ["-r", "./.pnp.js", "-r", "ts-node/register"],
        "skipFiles": ["<node_internals>/**", "node_modules/**"],
        "args": ["${workspaceFolder}/services/workflows/src/index.ts"]
    }
```
4. .yarnrc.yml
```yml
networkConcurrency: 16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://github.com/ojkelly/yarn.build/releases/download/v0.9.53/plugin-build.js"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  react-dev-utils@*:
    peerDependencies:
      webpack: ^4.0.0
      typescript: ^2.7.0 
  "@node-ts/logger-core@*":
    dependencies:
      tslib: "^2.0.0"
  "@node-ts/logger-winston@*":
    dependencies:
      tslib: "^2.0.0"
```

5.  try to run debugger
error:
```
/usr/local/bin/node -r ./.pnp.js -r ts-node/register /Users/valdestron/Projects/xxx/xx/services/workflows/src/index.ts
/Users/valdestron/Projects/xxx/xx/services/workflows/src/utils/injectableLogger.js:1
import { __decorate } from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/Users/valdestron/Projects/xxx/xx/.pnp.js:29848:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/valdestron/Projects/xxx/xx/services/workflows/src/index.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/valdestron/Projects/xxx/xx/.yarn/$$virtual/ts-node-virtual-259999f22d/0/cache/ts-node-npm-9.1.0-a67f8fc398-4735671aab.zip/node_modules/ts-node/src/index.ts:1056:23)
.yarn/cache/source-map-support-npm-0.5.19-65b33ae61e-59d4efaae9.zip/node_modules/source-map-support/source-map-support.js:478
Process exited with code 1

```

**Environment if relevant (please complete the following information):**

 - VSCode Version: November 2020 (version 1.52)
 - OS Version: macOS Catalina
 - Node Version: v14.15.1
 - Yarn Version 2.4.0

**Additional context**

Other services does not face the debugger issues in vscode, those without this `packageExtensions` hacks.
I found one related issue in vscode https://github.com/microsoft/vscode/issues/102834#issuecomment-715341161 but registered issue here because it is related with `packageExtensions` configuration.
