### ISSUE TITLE
[Bug] `yarn dedupe` does not deduplicate ^5.4.1/5.7.0 and ^5.6.0/5.6.0

### ISSUE THREAD

**Issue by Knagis** [yarnpkg/berry#2377]
- [ ] I'd be willing to implement a fix

**Describe the bug**

See the yarn.lock fragment below. It clearly can be deduplicated by moving ^5.6.0 to version 5.7.0. However,

```
>yarn dedupe
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ No packages can be deduped using the highest strategy
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
```

Deleting the ^5.6.0 section manually and running `yarn` does resolve ^5.6.0 to 5.7.0.

**To Reproduce**

```
"enhanced-resolve@npm:^5.4.1":
  version: 5.7.0
  resolution: "enhanced-resolve@npm:5.7.0::__archiveUrl=https%3A%2F%2Fdomain.com%3A443%2Fapi%2Fnpm%2Fnpm%2Fenhanced-resolve%2F-%2Fenhanced-resolve-5.7.0.tgz"
  dependencies:
    graceful-fs: ^4.2.4
    tapable: ^2.2.0
  checksum: 545cfa659e9cdccf1240bccbbd1791db7ec589979d71b35df5aeaf872dd8d13fab379ad73fa960f4cb32963b85492792c0fb0866f484043740014824ae6088b9
  languageName: node
  linkType: hard

"enhanced-resolve@npm:^5.6.0":
  version: 5.6.0
  resolution: "enhanced-resolve@npm:5.6.0::__archiveUrl=https%3A%2F%2Fdomain.com%3A443%2Fapi%2Fnpm%2Fnpm%2Fenhanced-resolve%2F-%2Fenhanced-resolve-5.6.0.tgz"
  dependencies:
    graceful-fs: ^4.2.4
    tapable: ^2.2.0
  checksum: c43bc831c7b8173b948148ede388501174474dcf8cc7c1888b7d13e58bf59aab52f5976625ec016ca821f6ff4ba140e57f0a4416e48a8347b46271b077d9f178
  languageName: node
  linkType: hard
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10 2004
 - Node version: 12.13.1
 - Yarn version: 2.4.0
