### ISSUE TITLE
[Bug] Yarn 2 "Unrecognized or legacy configuration settings found" npmScopes

### ISSUE THREAD

**Issue by Smbkilla** [yarnpkg/berry#2430]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I've tried upgrading my project to Yarn 2. I've followed steps for migration but got `"Unrecognized or legacy configuration settings found" npmScopes` error. To ensure the problem is not with my local machine or project I've reproduced issue in fresh install of WSL (Windows subsystems for Linux) and newly created react app `yarn create react-app my-app`

**To Reproduce**

1. Create new react app `yarn create react-app my-app`
2. ` npm install -g yarn`
3. `cd my-app`
4. `yarn set version berry`
5. Add `nodeLinker: node-modules` to my-apps .yarnrc.yml file
6. Add `nodeScopes` to my-apps .yarnrc.yml file
EDIT:
my-apps .yarnrc.yml file now looks like:
```
yarnPath: .yarn/releases/yarn-sources.cjs
nodeLinker: node-modules
npmScope:
  company:
    npmRegistryServer: "https://example.repo/npm"
    npmAuthIdent: "username:password"
```
7. `yarn install` produces the error

Note: Same can be reproduced in fresh WSL with fresh nodejs, npm and yarn installs

**Environment if relevant (please complete the following information):**

 - OS: [Windows 10]
 - Node version [12.18]
 - Yarn version [1.2.10]
