### ISSUE TITLE
How do we login to a registry in non-interactive?

### ISSUE THREAD

**Issue by stavalfi** [yarnpkg/berry#2503]
I couldn't find any full working example about that.

.yarnrc.yml
```
npmPublishRegistry: "http://localhost:34873"

npmRegistries:
  //localhost:
    npmAuthIdent: "123:123"

npmRegistryServer: "http://localhost:34873"

unsafeHttpWhitelist:
  - localhost
```

* I'm using local `verdaccio` which is pre-configured to have username/password 123/123.

when running `yarn npm login` it requests username and password.

I feel stupid when I desperately trying to figure out how to do such a simple task.

Thanks a lot.
