### ISSUE TITLE
[Bug] Libzip Error in Create React App 4 Project

### ISSUE THREAD

**Issue by ChiefORZ** [yarnpkg/berry#2642]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When working with the hot-reloaded dev environment of create-react-app (we have version ^4.0.2) - something crashes with the following error message:

```
[1] Compiling...
[1] 
[1] events.js:291
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] Error [Libzip Error]: Can't open file: No file descriptors available
[1] Require stack:
[1] - /Users/username/dev/data-quality-monitoring/.yarn/unplugged/jest-worker-npm-26.6.2-46cbcd449f/node_modules/jest-worker/build/workers/threadChild.js
[1]     at ZipFS.makeLibzipError (/Users/username/dev/data-quality-monitoring/.pnp.js:49419:25)
[1]     at new ZipFS (/Users/username/dev/data-quality-monitoring/.pnp.js:49390:20)
[1]     at ZipOpenFS.getZipSync (/Users/username/dev/data-quality-monitoring/.pnp.js:51462:18)
[1]     at ZipOpenFS.makeCallSync (/Users/username/dev/data-quality-monitoring/.pnp.js:51329:17)
[1]     at ZipOpenFS.existsSync (/Users/username/dev/data-quality-monitoring/.pnp.js:50750:17)
[1]     at VirtualFS.existsSync (/Users/username/dev/data-quality-monitoring/.pnp.js:48570:24)
[1]     at applyNodeExtensionResolution (/Users/username/dev/data-quality-monitoring/.pnp.js:52551:23)
[1]     at resolveUnqualified (/Users/username/dev/data-quality-monitoring/.pnp.js:53044:27)
[1]     at resolveRequest (/Users/username/dev/data-quality-monitoring/.pnp.js:53076:14)
[1]     at Object.resolveRequest (/Users/username/dev/data-quality-monitoring/.pnp.js:53148:26)
[1] Emitted 'error' event on process instance at:
[1]     at emitUnhandledRejectionOrErr (internal/event_target.js:541:11)
[1]     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:356:9)
[1]     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
[1]   code: 'ZIP_ER_OPEN'
[1] }
[1] CHOKIDAR_USEPOLLING=0 ESLINT_NO_DEV_ERRORS=true react-app-rewired start
```

**To Reproduce**

```json
// package.json
{
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "^4.0.2"
  },
  "dependenciesMeta": {
    "jest-worker": {
      "unplugged": true
    }
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@types/react": "^16.9.36",
    "babel-core": "bridge",
    "babel-eslint": "^10.1.0",
    "concurrently": "^5.3.0",
    "eslint": "^7.12.1",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-node": "^0.3.3",
    "eslint-plugin-graphql": "^4.0.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "jest-worker": "^26.6.2",
    "lint-staged": "^10.2.10",
    "prettier": "^2.1.2",
    "typescript": "^3.9.5"
  },
  "name": "data-quality-monitoring",
  "scripts": {
    "build": "DISABLE_ESLINT_PLUGIN=true react-scripts build",
    "dev": "CHOKIDAR_USEPOLLING=0 ESLINT_NO_DEV_ERRORS=true react-scripts start",
    "eject": "react-scripts eject"
  }
}

```

```yaml
enableMirror: true

packageExtensions:
  react-scripts@*:
    dependencies:
      eslint-plugin-prettier: "*"
      eslint-plugin-simple-import-sort: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.1.cjs
```

the dev server will not crash immediately, but when you do a lot of work and save often (for me once an hour) it will crash with the error.

sidenote: as you can see, i tried to add `jest-worker` as a dependency and unplugging it (because its an zip error - i thought it might fix the error).

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v14.8.0
 - Yarn version: 2.4.1
