### ISSUE TITLE
[Feature] Deep`npmScopes` merging

### ISSUE THREAD

**Issue by dchambers** [yarnpkg/berry#2648]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Setting up local auth credentials for a private scoped repository requires the developer to run `yarn npm login --scope <scope-name>`, and to enter their login details as requested. The result of running this command is the creation of a `~/.yarnrc.yml` file containing an auth token, like so:

```
npmScopes:
  myscope:
    npmAuthToken: <AUTH-TOKEN>
```

This only works provided that the configuration for this scope has already been defined, for example we might define the scope in the `.yarnrc.yml` file for the repository like so:

```
nodeLinker: node-modules
npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  myscope:
    npmPublishRegistry: "<REGISTRY-URL>"
    npmRegistryServer: "<REGISTRY-URL>"
    npmAlwaysAuth: true
```

However, this doesn't actually work since, although map values within the config are merged based on their key names, this isn't done recursively (e.g. `myscope` is also a map).

**Describe the solution you'd like**

I'd like developer on-boarding to just be to run `yarn npm login --scope myscope`.

**Describe the drawbacks of your solution**

It might possibly not make sense to offer deep merging for all current maps (e.g. `packageExtensions`?) or for all future maps?

**Describe alternatives you've considered**

Create a custom command for our sole usage (e.g. `yarn login`) that creates a `~/.yarnrc.yml` on the developer's behalf (needed for CI anyway) before running `yarn npm login --scope myscope`.
