### ISSUE TITLE
[Feature] Only Refetch Checksums When Running yarn install --check-cache

### ISSUE THREAD

**Issue by Kurt-von-Laven** [yarnpkg/berry#2918]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

`yarn install --check-cache` is very slow compared to the vast majority of other yarn operations. When the security `--check-cache` offers is needed, most of the benefit of zero installs is lost.

**Describe the solution you'd like**

I propose adding a configuration option to yarn that controls what the cache is checked against, defaulting to the npm registry but supporting local directories. This would allow the use of CI caching to improve the performance of `--check-cache`.

**Describe the drawbacks of your solution**

Yarn already offers a great many configuration options, and adding one more dilutes all the others. My proposal introduces extra complexity into the implementation of `--check-cache`.

**Describe alternatives you've considered**

The `--check-cache` flag is already in the core, and the proposed change does not break the CLI API, so a much faster version would also belong in the core. I have considered ceasing to use `--check-cache` in CI in the interest of performance, but this sacrifices security. I have considered only using `--check-cache` in builds on feature branches that modify yarn.lock, but this assumes that previous builds succeeded.

**Comment by Kurt-von-Laven** [comment]
I realized that no modification to Yarn is needed. The insight here is to cache an empty file rather than the dependencies. Here is an example of GitHub Actions steps that only check the cache when it hasn't previously been checked:

```yaml
      - name: Cache the fact that we have checked the yarn cache.
        id: yarn-cache
        uses: actions/cache@v2.1.6
        with:
          path: .cacheChecked
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies without refetching on cache hit.
        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        run: yarn install --immutable --immutable-cache
      - name: Install dependencies, refetching on cache miss for added security.
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: |
          # See https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
          yarn install --immutable --immutable-cache --check-cache
          touch .cacheChecked
```

Is there a more appropriate place where this might be documented?
