### ISSUE TITLE
[Bug?]: `yarn config unset changesetBaseRefs` breaks `.yarnrc.yml`

### ISSUE THREAD

**Issue by AlCalzone** [yarnpkg/berry#3072]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using `yarn config unset changesetBaseRefs`, the config file gets overwritten with `true`.

### To reproduce

Put the following into your `.yarnrc.yml`:
```yml
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.0.0-rc.6.cjs
```

Execute
```
$ yarn config unset changesetBaseRefs
➤ YN0000: Successfully unset changesetBaseRefs
```

Look at `.yarnrc.yml`:
```yml
true
```

### Environment

 System:
    OS: Windows 10 10.0.19041
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.2.0 - ~\AppData\Local\Temp\xfs-a5b6f7af\node.CMD
    Yarn: 3.0.0-rc.6 - ~\AppData\Local\Temp\xfs-a5b6f7af\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
