### ISSUE TITLE
[Bug?]: packageExtensions patches don't accept relative paths

### ISSUE THREAD

**Issue by elado** [yarnpkg/berry#3182]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Using a `patch:` in `packageExtensions` with a relative path to the patch, relative to the yarnrc file, throws an error that the file wasn't found:

```json
// package.json
{
  "name": "yarn3test",
  "version": "1.0.0",
  "dependencies": {
    "is-even": "^1.0.0"
  }
}
```

```yml
# .yarnrc.yml
packageExtensions:
  is-even@1.0.0:
    dependencies:
      lodash.noop: "patch:lodash.noop@2.4.1#./patches/lodash.noop.diff"
```

Error:

```
Error: lodash.noop@patch:lodash.noop@2.4.1#./patches/lodash.noop.diff::locator=is-even%40npm%3A1.0.0:
ENOENT: no such file or directory, open 'node_modules/is-even/patches/lodash.noop.diff'
```

If I use an absolute path, it works
```yml
lodash.noop: "patch:lodash.noop@2.4.1#/path/to/patches/lodash.noop.diff"
```

### To reproduce

// TODO

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.16.1 - /private/var/folders/vp/0st2qkvn1r30cz12p588767w0000gp/T/xfs-b0fbf0e7/node
    Yarn: 3.0.0 - /private/var/folders/vp/0st2qkvn1r30cz12p588767w0000gp/T/xfs-b0fbf0e7/yarn
    npm: 6.14.12 - ~/.nvm/version/npm
```
