### ISSUE TITLE
[Bug?]: yarn resolutions are ignored

### ISSUE THREAD

**Issue by vecerek** [yarnpkg/berry#3323]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I'm trying to solve a type error by setting a resolution because earlier versions of a nested dependency are known to be working. An excerpt of my yarn.lock file:

```
"@types/pino@npm:5.8.10":
  version: 5.8.10
  resolution: "@types/pino@npm:5.8.10"
  dependencies:
    "@types/node": "*"
    "@types/pino-std-serializers": "*"
    "@types/sonic-boom": "*"
  checksum: 4a0431a5e61262be1be256bdbe35642362d748b940804d68d3b8170e9c600600632daa5bbe9683e2a05658109b454233b7af9d7afc9a1771ab12a5926e02250d
  languageName: node
  linkType: hard

"@types/sonic-boom@npm:*":
  version: 2.1.0
  resolution: "@types/sonic-boom@npm:2.1.0"
  dependencies:
    sonic-boom: "*"
  checksum: db178afd930ea8b14defc3b0bd934a332d877920f5d82eeaed0326e5514a7d3a13bc7932b022ee86903815e57bd3f3ebd1fd7ce4a23dc70a37db2c736b67bb2f
  languageName: node
  linkType: hard
```

With the following resolution in my `package.json`, I would expect the yarn.lock file to include `@types/sonic-boom` to be pinned to version `0.7.0` instead of `2.1.0`.
```json
"resolution": {
  "**/@types/sonic-boom": "0.7.0"
}
```

### To reproduce

```json
{
  "name": "yarn-resolution-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@types/pino": "5.8.10",
    "pino": "5.13.2"
  },
  "resolution": {
    "**/@types/sonic-boom": "0.7.0"
  }
}
```

And then run:
```sh
yarn set version berry
yarn install
```

### Environment

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - /private/var/folders/m8/gznlbcs569z354vsbkhkh7y40000gq/T/xfs-4c5e519d/node
    Yarn: 3.0.1 - /private/var/folders/m8/gznlbcs569z354vsbkhkh7y40000gq/T/xfs-4c5e519d/yarn
    npm: 6.14.13 - /var/folders/m8/gznlbcs569z354vsbkhkh7y40000gq/T/fnm_multishells/44066_1629382931965/bin/npm

### Additional context

I wanted to use Sherlock for reproduction but couldn't figure out how to run expectations against the produced yarn.lock file. Any help with that would be appreciated 🙂
