### ISSUE TITLE
[Bug?]: Couldn't find a script named "constraints"

### ISSUE THREAD

**Issue by ChiefORZ** [yarnpkg/berry#3347]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

While trying to install the **constraints** plugin and executing it - it fails with following error message:
```
➜ yarn constraints
Usage Error: Couldn't find a script named "constraints", but a matching command can be found in the constraints plugin. You can install it with "yarn plugin import constraints".
```

why does yarn look after a script when it should clearly look for the plugin?

### To reproduce

```sh
➜ yarn plugin list
➤ YN0000: @yarnpkg/plugin-constraints [experimental]
➤ YN0000: @yarnpkg/plugin-hello-world [experimental]
➤ YN0000: @yarnpkg/plugin-exec [experimental]
➤ YN0000: @yarnpkg/plugin-interactive-tools [experimental]
➤ YN0000: @yarnpkg/plugin-stage [experimental]
➤ YN0000: @yarnpkg/plugin-typescript [experimental]
➤ YN0000: @yarnpkg/plugin-version [experimental]
➤ YN0000: @yarnpkg/plugin-workspace-tools [experimental]
➤ YN0000: Done in 0s 286ms

➜ yarn plugin import @yarnpkg/plugin-constraints
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/master/packages/plugin-constraints/bin/%40yarnpkg/plugin-constraints.js
➤ YN0000: Saving the new plugin in .yarn/plugins/@yarnpkg/plugin-constraints.cjs
➤ YN0000: Done in 0s 815ms

➜ yarn constraints
Usage Error: Couldn't find a script named "constraints", but a matching command can be found in the constraints plugin. You can install it with "yarn plugin import constraints".
```

my `.yarnrc.yml`looks like that:

```yml
enableMirror: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.1.cjs
```

### Environment

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.8.0 - /private/var/folders/r4/h_b0g83n16zd6q2b_ttdb5500000gn/T/xfs-83fd8e63/node
    Yarn: 2.4.1 - /private/var/folders/r4/h_b0g83n16zd6q2b_ttdb5500000gn/T/xfs-83fd8e63/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
