### ISSUE TITLE
[Feature] File protocol should not include gitignored / npmignored files

### ISSUE THREAD

**Issue by borekb** [yarnpkg/berry#3356]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

I have an `app` that depends on `lib` via the `file:` protocol:

```js
// app/package.json
{
  "dependencies": {
    "lib": "file:../lib"
  }
}
```

In `app/yarn.lock`, I'll get something like this after running `yarn`:

```yaml
"lib@file:../lib::locator=root-workspace-0b6124%40workspace%3A.":
  version: 0.0.0
  resolution: "lib@file:../lib#../lib::hash=faeeac&locator=root-workspace-0b6124%40workspace%3A."
  dependencies:
    lodash: 4.17.21
  checksum: 1bb9baca9fcaed71f740e7c5a68af31e2d2e711764cd6c7f374b89f8a8e36ac62ba257caf469b28e09ceab5f9c17afe9d4beee22902cfe6773c6992bbe54e760
  languageName: node
  linkType: hard
```

The problem is that the hash and a checksum in the lockfile are calculated from the `a` directory as a whole, including files like `.DS_Store`, node_modules or any gitignored files. Changing any of those will produce a new ["folderHash"](https://github.com/yarnpkg/berry/blob/2021f4780a1d75c800d1776b9ada8b841f8f922b/packages/plugin-file/sources/FileResolver.ts#L70) and a checksum:

```diff
"lib@file:../lib::locator=root-workspace-0b6124%40workspace%3A.":
  version: 0.0.0
- resolution: "lib@file:../lib#../lib::hash=faeeac&locator=root-workspace-0b6124%40workspace%3A."
+ resolution: "lib@file:../lib#../lib::hash=977560&locator=root-workspace-0b6124%40workspace%3A."
  dependencies:
    lodash: 4.17.21
- checksum: 1bb9baca9fcaed71f740e7c5a68af31e2d2e711764cd6c7f374b89f8a8e36ac62ba257caf469b28e09ceab5f9c17afe9d4beee22902cfe6773c6992bbe54e760
+ checksum: db4f858cfc4305daa6174d77b8a59aded15e3959d018c60b7136d3f3f430b50c1a1a51b65db5ae77de124b2a39b4aac04db1c6a5bd3b3097cc7c830273752f74
  languageName: node
  linkType: hard
```

In practice, we see a changed `yarn.lock` all the time and need to revert it manually. We wish these changes in gitignored / npmignored files didn't change the lockfile.

Also, I think that copying node_modules from the referenced package might lead to "incorrect installs" – `lib` might have `node_modules` installed or not, which might affect which versions of packages `app` resolves. (In general, I could have also messed with `lib/node_modules` manually and it feels wrong that this should affect `app`.)

**Describe the solution you'd like**

I think that the hash should use the same helper functions as `yarn pack` (probably functions like [`getPackList`](https://github.com/yarnpkg/berry/blob/2021f4780a1d75c800d1776b9ada8b841f8f922b/packages/plugin-pack/sources/packUtils.ts#L156) in `plugin-pack/sources/packUtils.ts`).

**Describe the drawbacks of your solution**

It's a change in behavior and maybe someone wants their dependencies to be re-fetched into the cache even if files like `.DS_Store` or something inside `node_modules` changes? I'm not sure.

**Describe alternatives you've considered**

Currently, in README, we instruct developers to revert `yarn.lock` changes that are caused by their local gitignored files.

(Note: this was initially discussed in Discord, see [this message](https://discord.com/channels/226791405589233664/654372321225605128/879645815080120350) and below.)

_Search terms: file protocol, gitignored files, gitignore, npmignored files, npmignore, `yarn pack`_
