### ISSUE TITLE
[Bug?]: Yarn monorepo - recursive node_modules symlinks

### ISSUE THREAD

**Issue by elliotdickison** [yarnpkg/berry#3380]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I upgraded to from Yarn 2.4.1 to 3.0.1 today. When I run `yarn install` for my monorepo, yarn creates a recursive symlink to each workspace within that workspace's node_modules. For example `worktree/packages/workspace-x/node_modules/workspace-x/node_modules/workspace-x/...`. Everything else about the install is correct. If I go through each workspace and delete `worktree/packaages/workspace-x/node_modules/workspace-x` then I'm in a valid state again. FWIW I get the exact same result for `yarn workspaces focus workspace-x --production` - every workspace that is installed references itself from its own node_modules.

### To reproduce

Getting "502: Bad Gateway" from the code sandbox. Will check back later and create a test case if I can.

### Environment

System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.5.0 - /private/var/folders/q_/y7w5vfj90n76sww7tczt1yqw0000gn/T/xfs-2c18d7b6/node
    Yarn: 3.0.1 - /private/var/folders/q_/y7w5vfj90n76sww7tczt1yqw0000gn/T/xfs-2c18d7b6/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm

### Additional context

Here's my .yarnrc.yml file. My node linker and hoisting limits are probably of note:

```yaml
nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
```
