### ISSUE TITLE
[Bug?]: yarn install link step very slow

### ISSUE THREAD

**Issue by rxliuli** [yarnpkg/berry#3476]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

It still takes a long time to use yarn to reinstall dependencies without any changes. I'm not sure what happened. We have 30 modules and nested workspaces.

Below is the output

```sh
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 480ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 765ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=1cc4b2 The platform win32 is incompatible with this module, link skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=1cc4b2 The platform win32 is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 38s 348ms
➤ YN0000: Done with warnings in 41s 807ms
```

### To reproduce

Unfortunately, only the production environment has this problem. I have not encountered this problem in my two personal projects. If there is any additional information I can provide, please let me know.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 16.9.1 - ~\AppData\Local\Temp\xfs-48c94d8d\node.CMD
    Yarn: 3.0.1 - ~\AppData\Local\Temp\xfs-48c94d8d\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^27.2.1 => 27.2.1
```

**Comment by rxliuli** [comment]
I guess it may be related to the deeply nested workspace. After I deleted the three-level nested workspace, it now takes 19s, but there may be other reasons

```sh
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 587ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 3s 106ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=1cc4b2 The platform win32 is incompatible with this module, link skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=1cc4b2 The platform win32 is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 19s 213ms
➤ YN0000: Done with warnings in 23s 133ms
```

**Comment by larixer** [comment]
@rxliuli What linker do you use?

**Comment by rxliuli** [comment]
> @rxliuli What linker do you use?

```yaml
compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
```
