### ISSUE TITLE
[Bug?]: Publishing to GCP npm registry generates broken manifest

### ISSUE THREAD

**Issue by lberrocal** [yarnpkg/berry#3502]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

I am working on scoped packages within a yarn berry workspace that is published to a google cloud platform artifact repository. I am able to publish the packages just fine but when I try to install them I get a E404 error because the tarball url in the manifest is not pointing to the right path.

The yarnrc file has the following entry for the scope 
```
npmScopes:
  [scope]:
    npmAlwaysAuth: true
    npmAuthToken: ${GCP_AUTH_TOKEN}
    npmPublishRegistry: "https://europe-north1-npm.pkg.dev/[gcp_project_name]/[artifact_repo_name]/"
    npmRegistryServer: "https://europe-north1-npm.pkg.dev/[gcp_project_name]/[artifact_repo_name]/"
```
When it comes to publishing via `yarn workspace [workspace_name] npm publish` yarn is able to use the [artifact_repo_name] path just fine which is why it's publishing correctly. Yet the tarball in the manifest is generated with the [artifact_repo_name] missing which is why when it's trying to download it, the resource cannot be found. This does not happen with plain `npm publish`

`yarn npm publish` dist properties in the package manifest
```json
"dist": {
  "integrity": "",
  "shasum": "",
  "tarball":"https://europe-north1-npm.pkg.dev/[gcp_project_name]/@[scope]/[component]/-/@[scope]/[package]-[version].tgz"
}
```

`npm publish` dist propesties in the package manifest
```json
"dist": {
  "integrity": "",
  "shasum": "",
  "tarball":"https://europe-north1-npm.pkg.dev/[gcp_project_name]/[artifact_repo_name]/@[scope]/[component]/-/@[scope]/[package]-[version].tgz"
}
```

### To reproduce

Reproduction script for this would be tricky since it depends on a GCP artifact repository to be set up. But It's basically initiating a workspace and publishing a package to a GCP artifact repository and trying to install the published package.
If needed I can try and set up one and share access to reproduce.

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 14.17.5 - /private/var/folders/n4/j15fwk2d51z1rvpbjlzjll6c0000gp/T/xfs-a7314565/node
    Yarn: 3.0.2 - /private/var/folders/n4/j15fwk2d51z1rvpbjlzjll6c0000gp/T/xfs-a7314565/yarn
    npm: 7.22.0 - /usr/local/bin/npm
```

### Additional context

The project is using [monodeploy](https://github.com/tophat/monodeploy) but I'm not sure it's relevant since the issue is occurring even when running yarn npm build
