### ISSUE TITLE
[Bug?]: .yarnrc.yml is overwritten when changing any configuration via cli or importing plugins

### ISSUE THREAD

**Issue by rafifos** [yarnpkg/berry#3528]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Let's imagine a project that have a `yarnrc.yml` file like below:

```yaml
# See https://yarnpkg.com/configuration/yarnrc for more info on configuring
# yarn v2+.

# The path of a Yarn binary, which will be executed instead of any other
# (including the global one) for any command run within the directory covered by
# the rc file. If the file extension ends with .js it will be required, and will
# be spawned in any other case.
#
# The yarnPath setting is currently the preferred way to install Yarn within a
# project, as it ensures that your whole team will use the exact same Yarn
# version, without having to individually keep it up-to-date.
yarnPath: ".yarn/releases/yarn-berry.cjs"

# If true, Yarn will ask for your guidance when some actions would be improved
# by being disambiguated. Enabling this setting also unlocks some features (for
# example the `yarn add` command will suggest to reuse the same dependencies as
# other workspaces if pertinent).
preferInteractive: true

# If true, the CLI will prefix most messages with codes suitable for search
# engines.
enableMessageNames: ${CI:-false}
```

When importing a plugin, for example, the entire file will be overwritten, removing the comments and re-ordering the entries, like so:

```yaml
enableMessageNames: "${CI:-false}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-berry.cjs

```

I haven't found anything about this behaviour on the website, so I'm assuming that it's something at least not documented, or it's unintended behaviour.

### To reproduce

1. Create a project with `yarn init`
2. Add a comment on the `.yarnrc.yml` file
3. Add a plugin
4. The file has been overwritten and your comment is lost

### Environment

```shell
System:
  OS: Linux 5.10 Pengwin 11 (bullseye)
  CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
Binaries:
  Node: 14.16.0 - /tmp/xfs-33cfd2a2/node
  Yarn: 3.0.2 - /tmp/xfs-33cfd2a2/yarn
  npm: 7.24.2 - ~/.asdf/installs/nodejs/lts/bin/npm
```

### Additional context

It happens both on WSL(2) and Linux (tested on Pop_OS! 20.04), but i'm pretty sure it's also happening on other platforms.
