### ISSUE TITLE
[Bug]: Yarn 2 has broken scoped authentication functionality since 2.2.0 version

### ISSUE THREAD

**Issue by beez0mbie** [yarnpkg/berry#3541]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Since yarn 2.2.0 version 

> yarn npm login --scope myCompany

Doesn't work as previous version, which has a correct behavior.

I used to Yarn 2.1.1 in our repository but when upgrade Yarn till 2.4.3 problem appears.
Here are steps and results with two different version of Yarn.

## Prerequisites

~/repository/.yarnrc.yml

```yml
npmScopes:
 myCompany:
  npmAlwaysAuth: true
  npmRegistryServer: "https://repo.myCompany.com/api/npm/npm-bld"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
```

## Steps

> yarn npm login --scope myCompany

### Creates

~/.yarnrc.yml

```yml
npmRegistries:
  "https://repo.myCompany.com/api/npm/npm-bld":
  npmAuthToken: <token>
```

> yarn config

### Output

```plain
➤ YN0000: npmRegistries Map(1) 
    { 'https://repo.myCompany.com/api/npm/npm-bld' => Map(3) 
        { 'npmAlwaysAuth' => false, 'npmAuthIdent' => null, 'npmAuthToken' => '********' } 
    }
➤ YN0000: npmRegistryServer 'https://registry.yarnpkg.com'
➤ YN0000: npmScopes Map(1) 
    { 'myCompany' => Map(5) 
        { 'npmAlwaysAuth' => true, 
        'npmAuthIdent' => null, 
        'npmAuthToken' => null,
        'npmPublishRegistry' => null, 
        'npmRegistryServer' => 'https://repo.myCompany.com/api/npm/npm-bld' 
        }
    }
```

> yarn add @myCompany/coolPackage

## Result

Successful authentication and downloading @myCompany/coolPackage package from scoped repository.

## Prerequisites

~/repository/.yarnrc.yml

```yml
npmScopes:
 myCompany:
  npmAlwaysAuth: true
  npmRegistryServer: "https://repo.myCompany.com/api/npm/npm-bld"

yarnPath: .yarn/releases/yarn-2.4.3.cjs
```

## Steps

> yarn npm login --scope myCompany

### Creates

~/.yarnrc.yml

```yml
npmScopes:
  myCompany:
    npmAuthToken: <token>
```

> yarn config

### Output

```plain
➤ YN0000: npmRegistries                 Map(0) {}
➤ YN0000: npmRegistryServer             'https://registry.yarnpkg.com'
➤ YN0000: npmScopes                     Map(1) 
    { 'myCompany' => Map(5) 
	    {'npmAlwaysAuth' => true, 
		'npmAuthIdent' => null, 
		'npmAuthToken' => null, 
		'npmPublishRegistry' => null, 
		'npmRegistryServer' => 'https://repo.myCompany.com/api/npm/npm-bld' 
		} 
	}
```

> yarn add @myCompany/coolPackage

## Result

Internal Error: Invalid authentication (as an anonymous user). Package was no downloaded.

### Output

```plain
➤ YN0027: @myCompany/coolPackage@unknown can't be resolved to a satisfying range:

Internal Error: Invalid authentication (as an anonymous user)
    at D (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:228065)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async v (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:229050)
    at async W.resolvers.getCandidates (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:240795)
    at async n.getCandidates (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:344518)
    at async K (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:36928)
    at async /Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:36175
    at async h (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:34661)
    at async F (/Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:35850)
    at async /Users/user/repository/.yarn/releases/yarn-2.4.3.cjs:2:39467

➤ Errors happened when preparing the environment required to run this command.
```

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.4.0 - /private/var/folders/zn/v8t9q4ln6qg3xsl5z5235nfw0000gn/T/xfs-4ccbb8d6/node
    Yarn: 2.4.3 - /private/var/folders/zn/v8t9q4ln6qg3xsl5z5235nfw0000gn/T/xfs-4ccbb8d6/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  npmPackages:
    jest: 26.2.2 => 26.2.2
```

### Additional context

I suppose that the problem with lost map in ~/.yarnrc.yml according to "npmRegistries" object.
Because of lost object:

```yml
npmRegistries:
  "https://repo.myCompany.com/api/npm/npm-bld":
  npmAuthToken: <token>
```

When I had researching this problem I found that this behavior appears in yarn 2.2.0 version.

Please return behavior of yarn 2.1.1 version.

**Comment by arcanis** [comment]
Yarn is an open-source project. If you have a frustrating bug with it you really want to see fixed, I encourage you to investigate it yourselves and open a PR!

Few of our core team use authenticated auth, so we usually can't even *try* our changes. We rely a lot on your help there.

**Comment by yarnbot** [comment]
Hi! 👋

This issue looks stale, and doesn't feature the `reproducible` label - which implies that you didn't provide a working reproduction using [Sherlock](https://yarnpkg.com/advanced/sherlock). As a result, it'll be closed in a few days unless a maintainer explicitly vouches for it or you edit your first post to include a formal reproduction (you can use the [playground](http://yarnpkg.com/playground) for that).

Note that we require Sherlock reproductions for long-lived issues (rather than standalone git repositories or similar) because we're a small team. Sherlock gives us the ability to check which bugs are still affecting the master branch at any given point, and decreases the amount of code we need to run on our own machines (thus leading to faster bug resolutions). It helps us help you! 😃

If you absolutely *cannot* reproduce a bug on Sherlock (for example because it's a Windows-only issue), a maintainer will have to manually add the `upholded` label. Thanks for helping us triaging our repository! 🌟

**Comment by Rush** [comment]
Reproducible and not stale.

**Comment by valentinpalkovic** [comment]
PTAL: https://github.com/yarnpkg/berry/issues/1319

So far you are not able to split configurations for npmScopes between a project configuration and your global configuration in your home directory. Delete the npmScope configuration in your project and define it completely in your global configuration. Then the authentication part will work as well.

**Comment by lensbart** [comment]
Probably related: using environment variables as npm auth token used to work, but doesn’t seem to work anymore.

The following works:

* Run `yarn install` with the following config:
  ```yml
  # .yarnrc.yml
  npmScopes:
    private:
      npmAlwaysAuth: true
      npmAuthToken: 'some-login-token'
      npmRegistryServer: https://something.codeartifact.eu-west-1.amazonaws.com/npm/something
  ```

The following doesn’t work, but should:

* Set `export AWS_CODE_ARTIFACT_AUTH_TOKEN=some-login-token` in the terminal to set environment variable
* Execute `echo $AWS_CODE_ARTIFACT_AUTH_TOKEN` in the terminal to confirm that this environment variable is indeed set to the same `some-login-token` as above
* Run `yarn install` with the following config:
  ```yml
  # .yarnrc.yml
  npmScopes:
    private:
      npmAlwaysAuth: true
      # Include trailing `-` to prevent `yarn` from failing in CI environment where `AWS_CODE_ARTIFACT_AUTH_TOKEN` is not available.
      npmAuthToken: ${AWS_CODE_ARTIFACT_AUTH_TOKEN-}
      npmRegistryServer: https://something.codeartifact.eu-west-1.amazonaws.com/npm/something
  ```

The problem is not with the `${}` syntax (for using environment variables, as explained in the [docs](https://yarnpkg.com/configuration/yarnrc)) by itself. We can confirm this by running `yarn config --verbose`. For security reasons, yarn doesn’t log the field for `npmAuthToken` but displays `'********'` instead. But we can confirm that the env var loads correctly by placing it in property (such as `npmRegistryServer`) and then running `yarn config --verbose`.

Thanks!

**Comment by rosanzheng** [comment]
I just had quite a hard time with the authentication part with `Yarn 3.1.0`, but I found the solution to it and hope I can save someone else from the struggles I've been having:

**Problem:**
My requirements were to publish one repository `@organization/test1` into the GitHub NPM registry. But I was not able to install this package from another repository lying within the same organization, because I defined my `.yarnrc.yml` wrongly.
Therefore, I received 404 errors and 401 errors when trying to install it.

**Solution:**
Here's what worked for me regarding the `.yarnrc.yml` file:

```
npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  <Your scope (case sensitive!)>:
    npmAlwaysAuth: true (optional I think)
    npmAuthToken: <Your Personal Access Token>
    npmRegistryServer: <URL to where your package is hosted, in our case it was https://npm.pkg.github.com>
```

**Comment by gferreri** [comment]
Is there any workaround to this bug that would allow installation of third-party packages from a private repo? In my case, I'd like to install `@fortawesome/fontawesome-pro` and I am unable to do so.

I've tried every workaround listed in this thread, including adding the information to my ~/.yarnrc.yml to no avail.

>Invalid authentication (as an unknown user)

**Comment by Rush** [comment]
```
yarn config set -H npmScopes.fortawesome.npmRegistryServer "https://npm.fontawesome.com/" && \
  yarn config set -H npmScopes.fortawesome.npmAuthToken "<YOUR_TOKEN>"
```

**Comment by lolmaus** [comment]
Hi!

How do I use a private npm registry (npm.pkg.github.com) **without checking the token into source control**?

I have this in `.yarnrc.yml`:

```
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true

npmScopes:
  foo:
    npmRegistryServer: https://npm.pkg.github.com
```

I have successfully added a token via `yarn npm login -s foo`.

When I do `yarn add -D @foo/bar`, I get this:

```
➤ YN0027: @foo/bar@unknown can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an anonymous user)

➤ Errors happened when preparing the environment required to run this command.
```

Please help.

**Comment by clayrisser** [comment]
It's best practice to use an environment variable, rather than hardcoding the token into the `.yarnrc.yml` file.

What worked for me is the following.

```yaml
npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  <Your scope (case sensitive!)>:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
    npmRegistryServer: https://npm.pkg.github.com
```

Then of course make sure you export your token before installing the package.

```sh
export NPM_AUTH_TOKEN=shhhh
```

If you are using yarn cache to cache the files in git lfs, you only need to authenticate the first time you download the packages. Once it's cached, it will just install the package from the cache.

**Comment by geoidesic** [comment]
I have a `.npmrc` file like this for our gitlab repo:
```
@portals:registry=https://gitlab.mycompany.io/api/v2/packages/npm/
//gitlab.mycompany.io/api/v2/packages/npm/:_authToken=blah
//gitlab.mycompany.io/api/v2/projects/101/packages/npm/:_authToken=blah
```

I can't for the life of me figure out how to replicate that with `.yarnrc.yml`

**Comment by jj811208** [comment]
> I have a `.npmrc` file like this for our gitlab repo:
> 
> ```
> @portals:registry=https://gitlab.mycompany.io/api/v2/packages/npm/
> //gitlab.mycompany.io/api/v2/packages/npm/:_authToken=blah
> //gitlab.mycompany.io/api/v2/projects/101/packages/npm/:_authToken=blah
> ```
> 
> I can't for the life of me figure out how to replicate that with `.yarnrc.yml`

My use case is the same as yours, you can try this

```
npmRegistries:
  //gitlab.mycompany.io/api/v2/packages/npm:
    npmAuthToken: blah
  //gitlab.mycompany.io/api/v2/projects/101/packages/npm:
    npmAuthToken: blah
npmScopes:
  portals:
    npmRegistryServer: "https://gitlab.mycompany.io/api/v2/packages/npm/"
```

**Comment by wsrast** [comment]
Update: I'm going to answer my own question here. I'm uncertain how this fix occurred to me, but it's certainly worth sharing.

The problem was in my existing yarn.lock file that was originally created with Yarn 1.x. For some reason, the package that I was referring to above had an entry in that yarn.lock (expected) which was causing Yarn 3.x to become very, very confused (unexpected). The fix was to go into that `yarn.lock` file, find the `@mycompany/react-native-copier` package resolution, and **delete it**. Then, run `yarn install` again.

Problem solved.

**Comment by alexgwolff** [comment]
I tested this and it worked `yarn@3.6.2`


`.yarnrc.yml`

```yml
npmScopes:
  <scope>:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://<url>'
```

`~/.yarnrc.yml`
```yml
npmRegistries:
  //<url>:
    npmAuthToken: <token>

```

**Comment by JohnGurin** [comment]
```ini
# .npmrc

@<scope>:registry = https://<url>/
//<url>/:_auth = <token>
always-auth = true
```
**works**. 

```yml
# ~/.yarnrc.yml

npmRegistries:
  //<url>/:
    npmAuthToken: <token>

npmScopes:
  <scope>:
    npmRegistryServer: https://<url>/
    npmAlwaysAuth: true
```
**does not work** in any combination 
(with/without trailing slashes, all in local/home config, with token in `npmScopes.<scope>.npmAuthToken` and etc).

More over, `npm` installs without an explicit version, `yarn` outputs this
```
>yarn add @<scope>/<package>
➤ YN0027: @<scope>/<package>@unknown can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an unknown user)

➤ Errors happened when preparing the environment required to run this command.
```
with the explicit version 
```
>yarn add @<scope>/<package>@0.3.43
➤ YN0000: ┌ Resolution step
➤ YN0041: │ @<scope>/<package>@npm:0.3.43: Invalid authentication (as an unknown user)
➤ YN0000: └ Completed in 0s 576ms
➤ YN0000: Failed with errors in 0s 581ms
```

```
win 11 x64
npm 9.8.1
yarn 3.6.3
node 19.9.0

**Comment by JohnGurin** [comment]
```ini
# .npmrc

@<scope>:registry = https://<url>/
//<url>/:_auth = <token>
always-auth = true
```
**works**. 

```yml
# ~/.yarnrc.yml

npmRegistries:
  //<url>/:
    npmAuthToken: <token>

npmScopes:
  <scope>:
    npmRegistryServer: https://<url>/
    npmAlwaysAuth: true
```
**does not work** in any combination 
(with/without trailing slashes, all in local/home config, with token in `npmScopes.<scope>.npmAuthToken` and etc).

More over, `npm` installs without an explicit version, `yarn` outputs this
```
>yarn add @<scope>/<package>
➤ YN0027: @<scope>/<package>@unknown can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an unknown user)

➤ Errors happened when preparing the environment required to run this command.
```
with the explicit version 
```
>yarn add @<scope>/<package>@0.3.43
➤ YN0000: ┌ Resolution step
➤ YN0041: │ @<scope>/<package>@npm:0.3.43: Invalid authentication (as an unknown user)
➤ YN0000: └ Completed in 0s 576ms
➤ YN0000: Failed with errors in 0s 581ms
```

```
win 11 x64
npm 9.8.1
yarn 3.6.3
node 19.9.0

**Comment by x318** [comment]
> ```ini
> # .npmrc
> 
> @<scope>:registry = https://<url>/
> //<url>/:_auth = <token>
> always-auth = true
> ```
> 
> **works**.
> 
> ```yaml
> # ~/.yarnrc.yml
> 
> npmRegistries:
>   //<url>/:
>     npmAuthToken: <token>
> 
> npmScopes:
>   <scope>:
>     npmRegistryServer: https://<url>/
>     npmAlwaysAuth: true
> ```
> 
> **does not work** in any combination (with/without trailing slashes, all in local/home config, with token in `npmScopes.<scope>.npmAuthToken` and etc).
> 
> More over, `npm` installs without an explicit version, `yarn` outputs this
> 
> ```
> >yarn add @<scope>/<package>
> ➤ YN0027: @<scope>/<package>@unknown can't be resolved to a satisfying range
> ➤ YN0041: Invalid authentication (as an unknown user)
> 
> ➤ Errors happened when preparing the environment required to run this command.
> ```
> 
> with the explicit version
> 
> ```
> >yarn add @<scope>/<package>@0.3.43
> ➤ YN0000: ┌ Resolution step
> ➤ YN0041: │ @<scope>/<package>@npm:0.3.43: Invalid authentication (as an unknown user)
> ➤ YN0000: └ Completed in 0s 576ms
> ➤ YN0000: Failed with errors in 0s 581ms
> ```
> 
> ```
> win 11 x64
> npm 9.8.1
> yarn 3.6.3
> node 19.9.0
> ```

Had a similar issue in my repo with nexus npm registry. Appears there is some issue with how yarn tries to authenticate or how it is resolves server response. Swapped out `npmAuthToken` -> `npmAuthIdent` and it worked

**Comment by phenomuser** [comment]
@x318 , your solution of swapping **npmAuthToken: base64(<user>:<pass>) -> npmAuthIdent: base64(<user>:<pass>) worked for me**

**Comment by x318** [comment]
@phenomuser, if you can provide `package.json` & `yarnrc` this would help. also, make sure `yarnrc` copied to docker as well

**Comment by sashless** [comment]
Oh well, this is totally broken. Please update the documentation at https://yarnpkg.com/configuration/yarnrc#npmAuthToken what **you** think is an `npmAuthToken` and `npmAuthIdent`

Most people here, maybe the whole world, seem to understand something different when reading `npmAuthToken` or `npmAuthIdent`.

Even gitlab does not imagine that the Gitlab Token **should** land in `npmAuthIdent` and **not** in `npmAuthToken`. See https://docs.gitlab.com/ee/user/packages/yarn_repository/
They think `GITLAB_NPM_TOKEN` should be set for `npmAuthToken`. Who could image that this is wrong.

This took me hours wtf.

For all others who try to "simply" transition from `npmrc` to `yarnrc.yaml`....from `yarn classic` to `yarn modern`...

When you have this: :`//gitlab.com/api/v4/projects/project-id/packages/npm/:_authToken'="${GITLAB_NPM_TOKEN}`

Then this is **notworking** : `npmAuthToken: ${GITLAB_NPM_TOKEN}`
But **this works:** `npmAuthIdent: ${GITLAB_NPM_TOKEN}`

**Comment by stassiek02** [comment]
After spending few hours on debugging why my private deps cannot be installed, I came to fix:
1. Do NOT add `@` in scope name eq. 
``` yml
npmScopes:
  "@myOrg":
    npmRegistryServer: https://<url>/
    npmAlwaysAuth: true 
```
  Idk why yarn will ignore that scope. 
  Instead remove `@` and use it like this
``` yml
npmScopes:
  myOrg:
    npmRegistryServer: https://<url>/
    npmAlwaysAuth: true 
```

2. If you were using auth token in `.npmrc` like this //registry.npmjs.org/:_auth=${NPM_TOKEN} 
in `.yarnrc.yml` use `npmAuthIdent` instead `npmAuthToken`
