### ISSUE TITLE
Migrated yarn v1.22 to v3.1 and yarn install is two times slower on GitLab CI

### ISSUE THREAD

**Issue by yhnavein** [yarnpkg/berry#3674]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I've decided to migrate from yarn v1 to the latest v3.1 and I see a significant increase in time spent on `yarn install` step on my GitLab runner.

On v1 `yarn install` takes around `45s` which is quite a reasonable time. (average from a dozen of runs)
On v3 `yarn install` takes around `107s` :( (average from 3 different runs)

I use only public npm packages and I do not (and I don't want to) to store my cache in the repository.
Most time is spent on the fetch step (`1m 27s` on average)

I thought that fetch times were improved, not degraded in the `berry` version :(

My `yarnrc.yml` for the reference:

```yml
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
```

Interestingly clean `yarn install` times run from my dev machine stayed very similar.

Any ideas why GitLab runner performs worse on yarn 3.1 ?

### To reproduce

`.gitlab-ci.yml`

```yml
stages:
  - build

BuildFrontend:
  stage: build
  except:
    - tags
  image: node:16-alpine
  variables:
    CI: 'false'
  script:
    - 'yarn install'
    - 'yarn build'
```

My `package.json`

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "npm run start",
    "start": "vite",
    "build": "vite build",
    "build:prod": "vite build",
    "test": "jest"
  },
  "dependencies": {
    "@devbookhq/splitter": "1.2.3",
    "@emotion/react": "11.5.0",
    "@emotion/styled": "11.3.0",
    "@hookform/resolvers": "2.8.2",
    "@mantine/core": "3.1.0",
    "@mantine/dates": "3.1.0",
    "@mantine/hooks": "3.1.0",
    "@mantine/notifications": "3.1.0",
    "@visx/visx": "2.2.2",
    "axios": "0.24.0",
    "axios-extensions": "3.1.3",
    "clsx": "1.1.1",
    "date-fns": "2.25.0",
    "dayjs": "1.10.7",
    "history": "5.0.1",
    "lodash-es": "4.17.21",
    "query-string": "7.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-financial-charts": "1.3.2",
    "react-hook-form": "7.18.0",
    "react-icons": "4.3.1",
    "react-masonry-css": "1.0.16",
    "react-number-format": "4.7.3",
    "react-router": "5.2.1",
    "react-router-dom": "5.3.0",
    "zod": "3.11.6"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "5.14.1",
    "@testing-library/react": "12.1.2",
    "@testing-library/react-hooks": "7.0.2",
    "@types/d3-array": "3.0.2",
    "@types/d3-format": "3.0.1",
    "@types/d3-time-format": "4.0.0",
    "@types/jest": "27.0.2",
    "@types/lodash-es": "4.17.5",
    "@types/react": "17.0.33",
    "@types/react-dom": "17.0.10",
    "@types/react-router-dom": "5.3.2",
    "@typescript-eslint/eslint-plugin": "5.2.0",
    "@typescript-eslint/parser": "5.2.0",
    "@vitejs/plugin-react-refresh": "1.3.6",
    "esbuild-jest": "0.5.0",
    "eslint": "8.1.0",
    "eslint-plugin-react": "7.26.1",
    "jest": "27.3.1",
    "jest-localstorage-mock": "2.4.18",
    "prettier": "2.4.1",
    "sass": "1.43.4",
    "swaggie": "0.6.7",
    "typescript": "4.4.4",
    "vite": "2.6.13"
  },
  "packageManager": "yarn@3.1.0"
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\xfs-ab931f68\node.CMD
    Yarn: 3.1.0 - ~\AppData\Local\Temp\xfs-ab931f68\yarn.CMD
    npm: 8.1.0 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    jest: 27.3.1 => 27.3.1
```
