### ISSUE TITLE
[Bug?]: Audit fails

### ISSUE THREAD

**Issue by artola** [yarnpkg/berry#3859]
### Describe the bug

Run `yarn npm audit` throws an error:

```text
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 405 (Method Not Allowed)
➤ YN0035:   Request Method: POST
➤ YN0035:   Request URL: https://npm.pkg.github.com/-/npm/v1/security/audits/quick

➤ Errors happened when preparing the environment required to run this command.
➤ This might be caused by packages being missing from the lockfile, in which case running "yarn install" might help.
```

### To reproduce

`yarn npm audit`

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 16.13.1 - /private/var/folders/2t/vh754bvs45303cbdj6b063jc0000gp/T/xfs-ae6787e7/node
    Yarn: 3.1.1 - /private/var/folders/2t/vh754bvs45303cbdj6b063jc0000gp/T/xfs-ae6787e7/yarn
    npm: 8.1.2 - /usr/local/Cellar/node@16/16.13.1/bin/npm
```

### Additional context

`.yarnrc.yml`

```yml
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmAuditRegistry: "https://npm.pkg.github.com"
```
