### ISSUE TITLE
Berry - .yarnrc.yml - yarnPath + npmScopes

### ISSUE THREAD

**Issue by petr-zatloukal** [yarnpkg/berry#4087]
Hi,
I have a problem with using fontawesome private repository

if I use this configuration repository is not found
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}
```

But without yarnPath everything works fine

```yml
nodeLinker: node-modules
enableGlobalCache: true

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}
```

Do you have any idea how to run it together?
