### ISSUE TITLE
[Bug?]: `yarn dedupe` doesn't work with `latest` version range

### ISSUE THREAD

**Issue by Methuselah96** [yarnpkg/berry#4216]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

`yarn dedupe` doesn't de-duplicate a package when one of the version ranges is `latest`

### To reproduce

`package.json` (`@mswjs/data` depends on `msw@lataest`)
```
{
  "name": "test-yarn-dedupe",
  "packageManager": "yarn@3.2.0",
  "dependencies": {
    "@mswjs/data": "^0.9.2",
    "msw": "^0.39.1"
  }
}
```

Relevant section of `yarn.lock`:
```
"msw@npm:^0.39.1":
  version: 0.39.1
  resolution: "msw@npm:0.39.1"
  dependencies:
    "@mswjs/cookies": ^0.1.7
    "@mswjs/interceptors": ^0.14.1
    "@open-draft/until": ^1.0.3
    "@types/cookie": ^0.4.1
    "@types/js-levenshtein": ^1.1.1
    chalk: 4.1.1
    chokidar: ^3.4.2
    cookie: ^0.4.2
    graphql: ^16.3.0
    headers-polyfill: ^3.0.4
    inquirer: ^8.2.0
    is-node-process: ^1.0.1
    js-levenshtein: ^1.1.6
    node-fetch: ^2.6.7
    path-to-regexp: ^6.2.0
    statuses: ^2.0.0
    strict-event-emitter: ^0.2.0
    type-fest: ^1.2.2
    yargs: ^17.3.1
  bin:
    msw: cli/index.js
  checksum: 15fae1d0e1af9c3f4c211e98f3633df8f4ec4988ace0491858f591e7ea7c6750d3f600d86bd5619b7eeaa751de1e5998ede5af223f056fd78d30582fe060034e
  languageName: node
  linkType: hard

"msw@npm:latest":
  version: 0.38.1
  resolution: "msw@npm:0.38.1"
  dependencies:
    "@mswjs/cookies": ^0.1.7
    "@mswjs/interceptors": ^0.13.3
    "@open-draft/until": ^1.0.3
    "@types/cookie": ^0.4.1
    "@types/js-levenshtein": ^1.1.1
    chalk: 4.1.1
    chokidar: ^3.4.2
    cookie: ^0.4.2
    graphql: ^16.3.0
    headers-polyfill: ^3.0.3
    inquirer: ^8.2.0
    is-node-process: ^1.0.1
    js-levenshtein: ^1.1.6
    node-fetch: ^2.6.7
    path-to-regexp: ^6.2.0
    statuses: ^2.0.0
    strict-event-emitter: ^0.2.0
    type-fest: ^1.2.2
    yargs: ^17.3.1
  bin:
    msw: cli/index.js
  checksum: 2e51936a18802a28282342a403e6aa538a2bc4de600d7dabb5ed93494f8e19f5273fa145830718e9680f7a6842f50d5c7e497b4844fd4b94b74803ccf656633a
  languageName: node
  linkType: hard
```

Run `yarn dedupe`. I would expect these two entries to be combined.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\Temp\xfs-83dff2e3\node.CMD
    Yarn: 3.2.0 - ~\AppData\Local\Temp\xfs-83dff2e3\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```
