### ISSUE TITLE
[Bug]: Yarn patches are not applied when node modules are loaded from a cache

### ISSUE THREAD

**Issue by milesj** [yarnpkg/berry#4231]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Short: Yarn patches (`.yarn/patches`) are not applied when node modules are restored from a cache (ignores the fetch step).

Long: In CI, we cache the `.yarn/cache` and `.yarn/install-state.gz` files based on the checksum of `yarn.lock`. This works pretty great and reduces the "fetch step" during `yarn install` down to 1 second. Overall, the entirety of yarn install takes less than 2 minutes (most of it is linking).

However, we've noticed the new patches do not get applied when we use this approach, while patches work locally. This is very apparent because builds crash in CI that were fixed by this patch, and the line numbers in the stack trace are pointing to the original pre-patch lines.

Since we have _no way_ to apply patches manually, we have to bust our CI cache for this to work correctly.

### To reproduce

Our problem is unique to Buildkite CI but it can maybe be replicated with GitHub actions: https://github.com/actions/setup-node

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.1 - /private/var/folders/93/p1hnsld57s79d4b503vnmq2w0000gn/T/xfs-b98bb0af/node
    Yarn: 3.1.0 - /private/var/folders/93/p1hnsld57s79d4b503vnmq2w0000gn/T/xfs-b98bb0af/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  npmPackages:
    jest: ^27.4.7 => 27.5.1
```

### Additional context

We're using Buildkite with the cache plugin:

```yaml
steps:
  - plugins:
    - <cache plugin>:
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
```
