### ISSUE TITLE
[Bug?]: `@swc/core` dependency not cached

### ISSUE THREAD

**Issue by julienfouilhe** [yarnpkg/berry#4256]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have added `@swc/core` as a dependency.

I have the following in my `.yarnrc.yml`:

```
nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x86
    - arm64
  os:
    - darwin
    - linux
```

When I run `yarn install` on my M1 macbook pro, `@swc/core` dependency `@swc/core-linux-arm64-musl` is not added to the yarn cache, thus resulting in discrepancies between machines.

### To reproduce

Add `@swc/core` as a dependency on a m1 mac, and try to run `yarn install --immutable --immutable-cache` on linux.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.2 - /private/var/folders/s9/x9s630sd4xd287p7xfg6r49h0000gn/T/xfs-c6a2588c/node
    Yarn: 3.2.0 - /private/var/folders/s9/x9s630sd4xd287p7xfg6r49h0000gn/T/xfs-c6a2588c/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

**Comment by merceyz** [comment]
This is happening because you're not specifying which `libc` version to use. We should update the documentation to include it as well.

**Comment by julienfouilhe** [comment]
Can confirm that having this in `yarnrc.yml` fixes the issue.

```
supportedArchitectures:
  cpu:
    - x86
    - arm64
  os:
    - darwin
    - linux
  libc:
    - glibc
    - musl
```
