### ISSUE TITLE
[Bug?]: Yarn 3 Error: EBUSY: resource busy or locked, rmdir '/root/app/node_modules'

### ISSUE THREAD

**Issue by bangbaew** [yarnpkg/berry#4259]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm currently switching from building node apps with Dockerfile (pre `yarn install` and build image) to use only docker-compose (use `yarn install` as entrypoint), which saves a lot of time and space, and mounting `node_modules` folder to a volume so I can still use the previous `node_modules` even after deleting the container and composing it up without needing to reinstall all the modules again.

I'm able to use the app fine and doesn't need to reinstall the modules when restarting the container, but when I re-compose the container (deleting and recreating), it reinstalls the modules because the old modules were deleted, so I need to mount the `node_modules` folder to a volume, which only works if I use Yarn 1 as the pictures below, it perfectly created a volume which points to `node_modules` and I'm able to recreate the container without needing to reinstall any modules.

![image](https://user-images.githubusercontent.com/29559559/159884501-665510e6-e457-4410-ad8d-ea8fc42e5c5f.png)
![image](https://user-images.githubusercontent.com/29559559/159884534-6e99f5d7-42cc-4052-bc17-14843e75f73c.png)
![image](https://user-images.githubusercontent.com/29559559/159884592-a253fec4-d719-4b35-814e-47c822285e1f.png)

However, if I run `yarn set version berry` on startup (looking if .yarnrc.yml exists, if not, then set version to berry and add node linker), and mount a `node_modules` volume, it logs `Error: EBUSY: resource busy or locked, rmdir '/root/app/node_modules'` and won't be able to start the app.
![image](https://user-images.githubusercontent.com/29559559/159884031-24a0d7a9-d696-437b-a96d-fd39ac09b502.png)
![image](https://user-images.githubusercontent.com/29559559/159884092-3719d20f-6e4c-45b8-8153-a2c683b4327b.png)

Is there any solution for this problem? I don't want to go back to Dockerfile method or run `yarn set version berry` manually in the cli, I don't want to keep `.yarnrc.yml` and `.yarn` folder in git as well.

### To reproduce

Create a volume which points to `node_modules`, and use entrypoint like this to set version berry automatically on first launch.
```
version: '3.9'
services:

  backend:
    container_name: backend
    image: node:alpine
    ports:
      - 30000:3000
    volumes:
      - .:/root/app
      - /root/app/dist
      - node_modules:/root/app/node_modules

    working_dir: /root/app
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "if [[ ! -f .yarnrc.yml ]]; then yarn set version berry && echo 'nodeLinker: node-modules' >> ./.yarnrc.yml; fi && yarn install && yarn dev"
      ]
    tty: true
    restart: always

volumes:
  node_modules:
```

### Environment

```shell
  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Binaries:
    Node: 17.7.1 - /tmp/xfs-43145e21/node
    Yarn: 3.2.0 - /tmp/xfs-43145e21/yarn
    npm: 8.5.2 - /usr/local/bin/npm
```

### Additional context

I tried using mutagen-compose, it worked fine but Antimalware Service Executable took 100% cpu usage on Windows, which completely slowed down my pc.
