### ISSUE TITLE
[Feature] Plugin provisioning via `.yarnrc.yml` instead of committing plugins to source

### ISSUE THREAD

**Issue by Eeemil** [yarnpkg/berry#4479]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

As a someone tasked with CI/CD, I would rather define plugins in a file and have yarn download the plugin during provisioning, rather than having to include `.yarn/plugins` in the source all repositories using yarn with plugins

**Describe the solution you'd like**

`yarnrc.yml` contains a ([undocumented](https://yarnpkg.com/configuration/yarnrc)) field for plugins, which is added when you run `yarn plugin import`. It contains a file path and a field "spec", which seems to be the plugin name.

However, this causes yarn to fail if the plugin configuration is present but `.yarn/plugins/` is empty. I filed a bug report that [this can put you in a catch-22 loop that it impossible to install plugins if they are not already installed](https://github.com/yarnpkg/berry/issues/4450), but apparently this is intended behavior.

I propose, first of all, that the plugins field in `yarnrc.yml` should get documented so that the intended behavior is not left to guesswork. Secondly, I propose that if `yarnrc.yml` contains the following:
```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
```
Then, running `yarn plugin import` (with no arguments), or something else like `yarn plugin sync`, then yarn would try to download the two plugins (if they do not already exist locally) and store them at the specified paths, rather than failing with `Internal Error: Cannot find module '/opt/build/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs' ...`. The `spec` field _should_ be sufficient for yarn to figure out where to download the plugins from.

Third, it would be nice to have a mechanism for version pinning plugins, e.g. something like
```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
    version: 1.0 # or "latest" if you want the same behavior as today
```
But that is not as important as the other two requests.
**Describe the drawbacks of your solution**

For the first two requests (documenting `plugins` in yarnrc.yml` and for yarn to automatically download plugins), the only drawback I see is that if the plugins are updated at the remote path between builds it could have unintended consequences. This would be solved by version pinning though.

As I understand, yarn plugin has no mechanism of plugin versioning, so this might require redesign of the plugin system.

**Describe alternatives you've considered**

Committing the `.yarn/plugins` directory works, but this adds unnecessary cruft of minified `.cjs` files of external dependencies in my repositories, which defeats the purpose altogether to use a package manager in the first place. I don't commit `node_modules` to my repositories... :sunglasses:
