### ISSUE TITLE
yarn 3.2 is not checking package.json engine

### ISSUE THREAD

**Issue by matart15** [yarnpkg/berry#4496]
package.json
```json
{
  "version": "0.0.0",
  "private": true,
  "engines": {
    "node": "18.1.0",
    "yarn": "3.2.0"
  },
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  ...
}
```

`node -v` : `v14.18.3`

`yarn install` just succeeds.

.yarnrc.yml
```yml
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
# ignore-engines:  false
# install:
#   ignore-engines: true
```

I tried 

.npmrc with `engine-strict = true` did not help.

Is there any config I am missing?
