### ISSUE TITLE
[Bug?]: `yarn version` fails on CI (GitHub Actions)

### ISSUE THREAD

**Issue by marcofugaro** [yarnpkg/berry#4548]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I am trying to use the [yarn version](https://yarnpkg.com/cli/version) command on GitHub Actions.

However it does not seem to work, this is the error:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/7217420/173685193-c9a54a0f-576b-4c08-a0e7-a2a6db16b1f8.png">

```
No ancestor could be found between any of HEAD and master, origin/master, upstream/master, main, origin/main, upstream/main
```

I am using the standard `actions/checkout@v2` to checkout the repo on GitHub Actions.
The branch where I trigger the action is the `dev` branch. So a custom one. Why `yarn version` only needs master/main branch?

### To reproduce

```yaml
on:
  push:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set the version of package.json
        run: yarn version 2.0.0
```

### Environment

```shell
Github Actions
```

### Additional context

I am using this to make a bot that auto-updates the package.json version wired to our internal semantic release system.
