### ISSUE TITLE
[Feature] More controlled architecture matrix 

### ISSUE THREAD

**Issue by seivan** [yarnpkg/berry#4604]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**
Allow defining CPI and OS together for more granular control. 

I am forced to get `Linux(arm64)` because I need `Darwin(arm64)`
```yaml
supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
```

**Describe the solution you'd like**

Maybe something like this would work: 
```yaml
supportedArchitectures:
  darwin:
  - arm64
  - x64
  linux:
  - x64

```
**Describe the drawbacks of your solution**

Might have missed something? 

**Describe alternatives you've considered**

Gotta say, `zero install`  is so good, I could learn to cope. Small thing, really.

**Comment by osdiab** [comment]
agreed, i had to add a number of unneeded OS packages to make the immutable install on our CI happy, which is bloating our git repo a bit.

**Comment by arcanis** [comment]
It'd be nice to add an `exclude` capability, a bit like it works for GitHub Actions' matrices. Wanna try doing a PR?

**Comment by yehonatanz** [comment]
It would be really nice for us as well as we've got the exact same use case - only need `arm64` for `darwin` to support M1/M2 while `linux` always uses `x64`. We could shave some dozens of MBs from our repo this way.

**Comment by PatrickShaw** [comment]
@seivan  do you propose a way for adding further filtering? We have a `libc` option in Yarn already (`musl` or `glibc`)

I imagine your schema would evolve into something like:

```yaml
supportedArchitectures:
  darwin:
  - arm64
  - x64
  linux:
  - cpu: x64
     libc: musl
 ```

but if that's the case I propose we just the whole structure flat which is what you'll find in https://github.com/yarnpkg/berry/pull/7243
