### ISSUE TITLE
Add support for .env file

### ISSUE THREAD

**Issue by jmariller** [yarnpkg/berry#4718]
Hi,

I am referring to an already existing issue which was closed, imho, without a proper resolution:
https://github.com/yarnpkg/berry/issues/2724

There was a pull request which was eventually rejected, with a proposed alternative solution (see one of the first messages from @paul-soporan):
https://github.com/yarnpkg/berry/pull/3938

Now I would really love to try and implement the proposal myself, unfortunately I do not have enough time and knowledge on my end. However with some hints and support I would be more than happy to help: is anybody willing to support this?

Many thanks!

**Comment by pi0neerpat** [comment]
Looking forward to that PR getting merged. Until then, the only solution is to inject the variable manually every time you run a command, which is not ideal.

```
GITHUB_PAT_PACKAGES=ghp_..... yarn install
```

**Comment by jmariller** [comment]
Thank you so much @arcanis for implementing this feature, very much appreciated :pray: Do you have any idea when the new version will be released with this change?

**Comment by merceyz** [comment]
@jmariller I've created a new release candidate so you can get it now by running
```sh
yarn set version canary
```

**Comment by jmariller** [comment]
awesome, thanks a lot @merceyz :+1:

**Comment by co-sic** [comment]
@jmariller is it working for you?
I get the error `Usage Error: Environment variable not found (NODE_AUTH_TOKEN) in /**/my-service/.yarnrc.yml (in /**/my-service/.yarnrc.yml)`

with my .yarnrc.yml file

```
nodeLinker: node-modules

injectEnvironmentFiles:
  - .env

npmScopes:
  my-organization:
    npmRegistryServer: https://npm.pkg.github.com/
    npmAuthToken: ${NODE_AUTH_TOKEN}

yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs

```
