### ISSUE TITLE
[Bug?]: install cache didn't save on cacheFolder

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/berry#4750]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

install cache didn't save on cacheFolder

### To reproduce

1. run yarn install

cached file should save in `T:\cache\yarn-cache`
but it save at `C:\Users\User\AppData\Local\Yarn\Berry\cache`

### Environment

```shell
yarn-3.2.2
```

### Additional context

~/.yarnrc.yml
```
npmRegistryServer: "https://registry.npmjs.org/"
cacheFolder: "T:\\cache\\yarn-cache"
enableColors: true
nodeLinker: node-modules

plugins:
  - path: "C:/Users/User/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs"
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: "C:/Users/User/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs"
    spec: "@yarnpkg/plugin-interactive-tools"

```

![image](https://user-images.githubusercontent.com/167966/184725032-c55ff5d5-1f98-4c2c-a895-16513a55f8d1.png)

![image](https://user-images.githubusercontent.com/167966/184726697-34a11ffd-8305-4e92-9f75-2b4793846f4a.png)
