### ISSUE TITLE
Yarn Syntax Error - .yarnrc.yml: SyntaxError: ';' expected

### ISSUE THREAD

**Issue by Shakti2303** [yarnpkg/berry#4808]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have an angular project with Yarn (3.2.3) installed. While running `yarn run format:check`, it reads .yarnrc.yml file and throws below error:
```
.yarnrc.yml: SyntaxError: ';' expected 
[error]   3 | npmRegistryServer: 'SOME_SERVER'
[error]   4 | npmScopes:
[error] > 5 |   "my-private-repo":
[error]     |                      ^
[error]   6 |     npmRegistryServer: 'SOME_SERVER'
[error]   7 |   ionic:
[error]   8 |     npmRegistryServer: 'SOME_SERVER'
```

### To reproduce

Here is my .yarnrc.yml configuration:
```yaml
yarnPath: ".yarn/releases/yarn-3.2.3.cjs"
nodeLinker: node-modules
npmRegistryServer: 'SOME_SERVER'
npmScopes:
  "my-private-repo":
    npmRegistryServer: 'SOME_SERVER'
  ionic:
    npmRegistryServer: 'SOME_SERVER'
enableStrictSsl: false
httpRetry: 2
httpTimeout: 60000
```
Syntax error is thrown at "my-private-repo" . I figured out that maybe the issue is with the hyphens in that private repository as when I removed that repo, the command passes successfully. I cannot rename that private repo as its a legacy repo. Any clues how to fix this issue ?

### Environment

```shell
Node Version : 14.15.4
Yarn : 3.2.3
macOS : 11.6.5
```

### Additional context

Syntax error is thrown at "my-private-repo" . I figured out that maybe the issue is with the hyphens in that private repository as when I removed that repo, the command passes successfully. I cannot rename that private repo as its a legacy repo. Any clues how to fix this issue ?
