### ISSUE TITLE
[Bug?]: yarn workspaces focus gives Internal Error: Invalid ident

### ISSUE THREAD

**Issue by bradtgmurray** [yarnpkg/berry#5061]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

```
$ yarn workspaces focus 'packages/api-server'
Internal Error: Invalid ident (packages/api-server)
    at Object.Zi (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:390:22149)
    at /Users/brad/beeper/beeper-services/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs:7:29002
    at Array.map (<anonymous>)
    at Ae.execute (/Users/brad/beeper/beeper-services/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs:7:28958)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ae.validateAndExecute (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:63:13148)
    at async LA.run (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:77:2354)
    at async LA.runExit (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:77:2538)
    at async i (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:446:12061)
    at async t (/Users/brad/beeper/beeper-services/.yarn/releases/yarn-3.2.4.cjs:446:10278)
```

### To reproduce

Proprietary repo unfortunately

.yarnrc.yaml
```
nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: "https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
```

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - /private/var/folders/pb/_bs5c8rj07392nmgt9w2lnvr0000gn/T/xfs-f469d919/node
    Yarn: 3.2.4 - /private/var/folders/pb/_bs5c8rj07392nmgt9w2lnvr0000gn/T/xfs-f469d919/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```
