### ISSUE TITLE
[Bug?]: How the version plugin is supposed to work?

### ISSUE THREAD

**Issue by blephy** [yarnpkg/berry#5109]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Hi,

After after reading many times the documentation, even if i did follow the [release-workflow tutorial](https://yarnpkg.com/features/release-workflow), `yarn version check` is always failing without taking into account previous command `yarn version check -i` committed before. it fail for every workspaces touched by a git changes without taking into account `.yarn/version` files.

```shell
@scope/my-package@workspace:. has been modified but doesn't have a release strategy attached
```
### To reproduce

From [contributing](https://yarnpkg.com/advanced/contributing)

```shell
git checkout -b my-feature
git checkout -
git reset --hard origin/master
git checkout -

# here i select decline for each workspace
yarn version check --interactive

# i precise here that git is tracking `versions` folder containing `yml`
git add .
git commit -m "chore(version): defer bump for my-feature"
git push

# here the command always failing - reporting every workspaces touched by a git changes
yarn version check
```

I did also try the method

```shell
git checkout -b my-feature
git checkout -
git reset --hard origin/master
git checkout -

# using workspaces foreach
yarn workspace foreach version decline --deferred

# i precise here that git is tracking `versions` folder containing `yml`
git add .
git commit -m "chore(version): defer bump for my-feature"
git push

# here the command always failing - reporting every workspaces touched by a git changes instead of 
yarn version check
```

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.11.0 - /private/var/folders/1f/d9r35kjs4l1bx93x8h1f35100000gp/T/xfs-a8962911/node
    Yarn: 3.3.0 - /private/var/folders/1f/d9r35kjs4l1bx93x8h1f35100000gp/T/xfs-a8962911/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
```

### Additional context

```yml
cacheFolder: ./.yarn/cache

constraintsPath: ./config/constraints/constraints.pro

changesetBaseRefs:
  - 'master'
  - 'origin/master'

defaultSemverRangePrefix: '^'

deferredVersionFolder: './.yarn/versions'

enableGlobalCache: false

enableTelemetry: false

initScope: ********

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: 'https://npm.pkg.github.com'

npmScopes:
  ********:
    npmAlwaysAuth: true
    npmAuthToken: '${XX_XX__XX__XX}'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

progressBarStyle: hogsfather

yarnPath: .yarn/releases/yarn-3.3.0.cjs
```
