### ISSUE TITLE
[Bug?]: Can't add a package which is from github registry, and it's public

### ISSUE THREAD

**Issue by angeousta** [yarnpkg/berry#5427]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have this `.yarnrc.yml` file 

```
nodeLinker: node-modules

npmScopes:
  <orgName>:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
```

Replace `<orgName>` with your org name

When I try to add a package by `yarn add @<orgName>/<packageName>`,  I get

` Invalid authentication (as an anonymous user)`

but it's a public package, so login is not required, why is yarn asking me for it?

### To reproduce

Create a project with the `.yarnrc.yml` file I provided linked to a public npm package from github packages.

### Environment

```shell
yarn 3.5.1

Error: Command failed: wmic os get Caption
```
