### ISSUE TITLE
yarn npm audit cannot find packages from custom registry server

### ISSUE THREAD

**Issue by johannesrue** [yarnpkg/berry#5533]
### Describe the bug

`yarn npm audit` fails due to response code `404` because a scoped package, hosted in a custom npm registry, cannot be found.   

```
yarn npm audit --severity moderate --recursive --environment production
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@myCustomScope/myCustomModule
``` 

It seems, the custom npm registry configurations are ignored, because it's trying to load it from `registry.yarnpkg.com`.

Running `yarn install` works fine, no errors there.    

My `.yarnrc.yml`  currently looks like this:  

```
enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  myCustomScope:
    npmRegistryServer: "https://my-custom.registry/api/v4/packages/npm/"
  myCustomScope2:
    npmRegistryServer: "https://my-custom.registry/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-sources.cjs
```

### To reproduce

1. Create a package.json with a dependency (I'm not sure if it only happens with scopes packages?) hosted in a custom npm registry.  
2. Add the custom npm registry url to the `.yarnrc.yml`
3. Run `yarn install` -> Should work
4. Run `yarn npm audit --severity moderate --recursive --environment production` -> Fails because package hosted in the custom npm registry cannot be found

### Environment

```shell
System:
  OS: openSUSE 15.4
  CPU: Core(TM) i9-12900K   3.20 GHz
Binaries:
  Node: 18.16.1
  Yarn: 4.0.0-rc.46.git.20230626.hash-30b0d09
  npm: 9.5.1
```
