### ISSUE TITLE
[Bug?]: `yarn plugin import` removes `injectEnvironmentFiles: []` from `.yarnrc.yml`

### ISSUE THREAD

**Issue by exKAZUu** [yarnpkg/berry#5545]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When adding plugin by `yarn plugin import ...`, `injectEnvironmentFiles: []` is removed in `.yarnrc.yml`.
(cf. https://github.com/yarnpkg/berry/pull/5531#issuecomment-1613672514)

Here are reproduction steps:

1. `yarn set version 4.0.0-rc.47`
2. `echo "yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs\ninjectEnvironmentFiles: []" > .yarnrc.yml`
3. `yarn plugin import https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js`
4. `cat .yarnrc.yml` does not include `injectEnvironmentFiles` like:

```yml
plugins:
  - checksum: f545f7b647a6c43a1df5c6091541c3c9d1f067db0c0d8cfe41178ac2e29c9d4d4c692c24935a4c66e7801ceee11b72dd4d75062d0fb4eff3135538deb6c4afc3
    path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.47.cjs
```

### To reproduce

```js repro
const fs = require('fs/promises');

await fs.appendFile('.yarnrc.yml', 'injectEnvironmentFiles: []');
expect(await fs.readFile('.yarnrc.yml', 'utf-8')).toContain('injectEnvironmentFiles');

await yarn('plugin', 'import', 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js');
expect(await fs.readFile('.yarnrc.yml', 'utf-8')).toContain('injectEnvironmentFiles');
```

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 20.2.0 - /private/var/folders/9p/8yqjg80d1n9dpmz33_v4hgj80000gn/T/xfs-69436567/node
    Yarn: 4.0.0-rc.47 - /private/var/folders/9p/8yqjg80d1n9dpmz33_v4hgj80000gn/T/xfs-69436567/yarn
    npm: 9.6.6 - ~/.asdf/shims/npm
  npmPackages:
    jest: 29.5.0 => 29.5.0
```
