### ISSUE TITLE
[Feature] 4rc.47+ node min version message improvement for yarn config

### ISSUE THREAD

**Issue by belgattitude** [yarnpkg/berry#5565]
- [ ] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Node 18.12 is required for upcoming yarn 4.0.0 (enforced since rc.47) and that's great imho.

Message is super clear :pray: 

```
Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.1). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.

━━━ Yarn Package Manager - 4.0.0-rc.47 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
``` 

I'd like to suggest one thing to prevent confusion when upgrading. 

On the CI, some users including myself are reading the yarn config. For example:

```yaml
    - name: ⚙️ Expose yarn config as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      working-directory: ${{ inputs.cwd }}
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
```

For an example: https://gist.github.com/belgattitude/042f9caf10d029badbde6cf9d43e400a

When doing so the message is limited to the last line which can create confusion:

![image](https://github.com/yarnpkg/berry/assets/259798/e63a91cc-e4a9-462b-8e9a-d9ac42460de3)

See also a user comment: https://gist.github.com/belgattitude/042f9caf10d029badbde6cf9d43e400a?permalink_comment_id=4615921#gistcomment-4615921

**Describe the solution you'd like**

The  `Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.1)` might be more clear when using `yarn config`. Just wanted to bring attention. I know it's an edge case. 

**Describe the drawbacks of your solution**

**Describe alternatives you've considered**
