### ISSUE TITLE
[Bug?]: illegal operation on a directory when using package.json scripts to a shell script

### ISSUE THREAD

**Issue by a666** [yarnpkg/berry#5669]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In version 3.6.2 having a packaje.json script that runs a shell script sends the following in version 3.6.2:
```shell
$ yarn compose
Internal Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:751:3)
    at $t.readSync (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:314:1260)
    at zR (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:423:663)
    at LB (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:423:1888)
    at async m9 (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:423:1934)
    at async wRe (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:422:3297)
    at async /home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:422:2583
    at async $t.mktempPromise (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:314:69436)
    at async Object.TB (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:422:2523)
    at async Fu.execute (/home/***/.cache/node/corepack/yarn/3.6.2/yarn.js:572:2017)
```
but in version 3.6.1 the script just runs
```shell
$ yarn compose
# prints the help message
Runs a ...
Usage: yarn run compose [-h] [-f]
```

### To reproduce

Having the following `package.json`:
```json
{
  "name": "test",
  "private": true,
  "packageManager": "yarn@3.6.2",
  "scripts": {
    "compose": "./compose.sh",
  }
}
```
And the following `compose.sh`
```bash
#!/usr/bin/env bash

echo Do you feel lucky punk?
```

Should be enough.

PS. BTW the link to https://yarnpkg.com/advanced/sherlock is broken.

### Environment

```shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 18.17.1 - /tmp/xfs-7f8286f6/node
    Yarn: 3.6.2 - /tmp/xfs-7f8286f6/yarn
    npm: 9.6.7 - ~/.cache/node/bin/npm
```

### Additional context

Considering how simple  this pattern is, probably will happen to any package.json script that runs any executable script (like php's vendor/bin/some_package_or_another).

**Comment by la-magra** [comment]
Isn't this a breaking change?

**Comment by danielpza** [comment]
I'm also seeing this issue on yarn rc v4 : `yarn-4.0.0-rc.50`

```
Internal Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:749:3)
    at Rn.readSync ([...]/.yarn/releases/yarn-4.0.0-rc.50.cjs:9:7517)
...
```

**Comment by DBosley** [comment]
I'm running into this issue with the latest versions of yarn (3.6.2 and 3.6.3) on a workspace enabled monorepo. The workspaces has the following dependency:
`"mini-css-extract-plugin": "0.4.5"`
I've traced the error in the yarn-3.6.3.cjs file. It seems to think mini-css-extract-pugin is a binary, but it's a directory.

I put a console log in this block of minified code (you can search for it in the yarn-3.6.3.cjs file)
`{let C=x.resolve(f,p);i.set(h,[g,K.fromPortablePath(C),zR(C)])}`
I changed it to:
`{let C=x.resolve(f,p);console.log(C);`i.set(h,[g,K.fromPortablePath(C),zR(C)])}`

This printed out `node_modules/mini-css-extract-plugin` in the console after a bunch of runnable files from the .bin folder. The rest of the outputs from this `C` variable were all files, while this was a folder.


My current workaround is to use 3.6.1 which does not seem to have the issue.

**Comment by DBosley** [comment]
Oh, I did also notice this in the yarn.lock
```
"mini-css-extract-plugin@npm:^0.4.1":
  version: 0.4.5
  resolution: "mini-css-extract-plugin@npm:0.4.5"
  dependencies:
    loader-utils: ^1.1.0
    schema-utils: ^1.0.0
    webpack-sources: ^1.1.0
  peerDependencies:
    webpack: ^4.4.0
  bin:
    mini-css-extract-plugin: ""
  checksum: 0e8722b879e078cbc4d31a6c3aaf410ccc185d12e4f414301c0c4586a8e0c5d56e39bd281a268e0324cc9c79cfe8a29b27d4cc02afaf805926d8c1769f9e40fe
  languageName: node
  linkType: hard
  ```
  notice the line saying it's a bin... That's definitely not right.
