### ISSUE TITLE
[Bug?]: --cache-check not working across OSes for conditional deps

### ISSUE THREAD

**Issue by sbonami** [yarnpkg/berry#5692]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In a zero-install setup, one would expect all packages to be installed into the cache. Specifically for packages with conditions like `@nx/nx-*-*` (installed with lerna), the installing OS environment only adds the packages for the matching OS.

While this starts to go slightly astray of the zero-install idea, it makes sense.
The challenge starts to ramp up when comparing the guidance to run install with `--cache-check` in a CI where the OS is different.

One potential solution might be guidance to build the yarn cache within the CI itself so that you're consistent, but this isn't without its own challenges: CI guidance is widely varied, it's still a departure from zero-install goodness, and it's not going to resolve a cache check run on someone's machine.

### To reproduce

```json package.json
{
  "name": "yarn-cache-os-issue-repro",
  "packageManager": "yarn@3.6.3",
  "dependencies": {
    "nx": "^16.7.4"
  }
}
```

<details><summary>Github Action</summary>
<p>

```yaml .github/workflows/ci.yml
name: "CI"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
```

</p>
</details> 

From a Mac M1 (arm64 architecture) 
```bash
yarn add nx
```

<details><summary>Example Conditions from nx deps</summary>
<p>

```yaml yarn.lock
"@nx/nx-darwin-arm64@npm:16.7.2":
  version: 16.7.2
  resolution: "@nx/nx-darwin-arm64@npm:16.7.2"
  conditions: os=darwin & cpu=arm64
  languageName: node
  linkType: hard

"@nx/nx-darwin-x64@npm:16.7.2":
  version: 16.7.2
  resolution: "@nx/nx-darwin-x64@npm:16.7.2"
  conditions: os=darwin & cpu=x64
  languageName: node
  linkType: hard
```

</p>
</details> 

From a CI or computer with a different architecture
```bash
yarn install --immutable --immutable-cache --check-cache
```

### Environment

```shell
System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 18.14.0 - /private/var/folders/p7/hp75q4357yl6zhlmwwqfr4qc0000gn/T/xfs-c1e4d1f1/node
  Yarn: 4.0.0-rc.50 - /private/var/folders/p7/hp75q4357yl6zhlmwwqfr4qc0000gn/T/xfs-c1e4d1f1/yarn
  npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
```

### Additional context

Public reproduction: https://github.com/sbonami/yarn-cache-os-issue-repro
