### ISSUE TITLE
yarn install (v4) will fail the first time with packages from private registry (artifactory).

### ISSUE THREAD

**Issue by danielplappert** [yarnpkg/berry#5890]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In our project we are currently using yarn v1. We are able to download packages from our private registry (artifactory). Our packages are scoped packages, which means our package.json looks like this:
```json
 ...
 "dependencies": {
    "@mui/icons-material": "^5.9.1",
    "@private/lib1": "1.2.2",
    "@private/lib2": "1.0.2",
 ...
```

With yarn v1 everything works fine. Now we want to upgrade to yarn v4. We migrated .npmrc to .yarnrc.yml 

```yaml
npmScopes:
  private:
    npmAlwaysAuth: true
    npmRegistryServer: "https://artifactory.company.com/artifactory/api/npm/private-npmjs/"
    npmAuthToken: MY_TOKEN
```

and also set yarn version to berry. So far so good. But the first time we run
```bash
yarn install
```
yarn failed with the following error:

```
➤ YN0001: │ Error: @private/lib1@npm:1.2.2: @private/lib1@npm:1.2.2::__archiveUrl=https%3A%2F%2Fartifactory.company.com%3A443%2Fartifactory%2Fapi%2Fnpm%2Fprivate-npmjs%2F%40private%2Flib1%2F-%2F%40private%2Flib1-1.2.2.tgz%23 isn't supported by any available resolver
```

When we remove our own (private) dependencies
```json
 "dependencies": {
    "@mui/icons-material": "^5.9.1",
 ...
```

and run ``yarn install`` again, yarn is downloading all packages without any error. After the first run of ``yarn install`` we can now add our dependencies again:

```json
 ...
 "dependencies": {
    "@mui/icons-material": "^5.9.1",
    "@private/lib1": "1.2.2",
    "@private/lib2": "1.0.2",
 ...
```

and re-run ``yarn install``. NOW the packages from our private registry are downloaded and installed as well. There are no errors.

It seems, that only the first time we run ``yarn install`` there is a problem with installing packages from our registry. The problem is, that this also happens in our gitlab pipelines, which means, we are currently unable to build our app with yarn v4.

### To reproduce

Create a project containing packages from a private registry using yarn v1. 

Upgrade to yarn v4 as described here: https://yarnpkg.com/migration/guide

After running ``yarn install``, installation will fail. Remove all packages of your private registry in your package.json, and re-run ``yarn install`` again. Installation will now succeed. Undo your changes in package.json and run ``yarn install`` again.

### Environment

```shell
System:
  OS: macOS 13.5.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Binaries:
  Node: 20.9.0 - /private/var/folders/bf/kpd557n94931bg65fm4mw7cm0000gn/T/xfs-246c0f58/node
  Yarn: 4.0.0 - /private/var/folders/bf/kpd557n94931bg65fm4mw7cm0000gn/T/xfs-246c0f58/yarn
  npm: 10.1.0 - /usr/local/bin/npm
  pnpm: 8.10.0 - /usr/local/bin/pnpm
```

**Comment by n3m6** [comment]
Same issue

**Comment by n3m6** [comment]
the following .yarnrc.yml file worked for some reason.
```
enableGlobalCache: true
checksumBehavior: reset
defaultSemverRangePrefix: ""
enableColors: true
enableConstraintsChecks: true
nmHoistingLimits: workspaces
nodeLinker: pnp
preferInteractive: false
yarnPath: .yarn/releases/yarn-4.0.2.cjs
npmRegistries:
  //gitlab.com/api/v4/projects/xxx/packages/npm/:
    npmAlwaysAuth: true
npmScopes:
  private:
    npmRegistryServer: ""
    npmAlwaysAuth: true
```

I suspect it has to do with nodeLinker, but I"m not sure.

**Comment by siosio34** [comment]
same issue too

**Comment by azeezat** [comment]
I deleted the yarn.lock file and installed the dependencies again and that fixed the error.

**Comment by yongsk0066** [comment]
same issue too

**Comment by laliux** [comment]
I had a similar issue, yarn v3.6.1, github npm registry. It worked for my **.yarnrc.yml** :


```
npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN}

npmScopes:
  myscope:
    npmRegistryServer: https://npm.pkg.github.com
```

The package.json for my package looks like:

```
{
  "name": "@myscope/my-package-name",
  "version": "1.0.10",
  "publishConfig": {
    "@myscope:registry": "https://npm.pkg.github.com"
  },
  ...
  "dependencies": {
    "aes-cross": "^1.1.2"
  }
}
```

**Comment by sumasagrp** [comment]
when you yarn install with internal repository it seems to create a resolution with __archiveURL pointing to that internal repository, when you cleaned and tried without internal repository it creates a yarn.lock file containing resolution without __archiveURL . This resolution is still able to be used with internal repository .  There should be an over rider to to ignore archiveURL because this issue breaks pipelines where development and build chains have different internal urls.

The fix is to use this sed -i -e "s#https://registry.yarnpkg.com/#{YOUR_CI_REGISTRY}#g" yarn.lock

i believe this used to work sed -i -e "/resolved:* .*$/d" yarn.lock which was cleaner but v4 requires resolution. 

Yarn team any suggestions ?  Respository such as artifactory might not have the desired url scheme but it would still be nice to have over ride features for users to get around issues like this.

**Comment by dnguyentien-lmi** [comment]
> I deleted the yarn.lock file and installed the dependencies again and that fixed the error.

This fixed it for me. Check if the yarn.lock has been migrated/converted to the new format. If not, then deleting it and re-running yarn install solves it

**Comment by scotteratigan** [comment]
I faced this issue migrating from yarn 1 to yarn 4 with a private npm server (artifactory). My fix was to first update to yarn 2 with `yarn set version 2.x` then run yarn install, which updates the lockfile to the new expected format, and then update to yarn 4 with `yarn set version berry` and then re-run yarn install.

**Comment by sankar-gp** [comment]
This is my .yarnrc.yml file

`nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

npmRegistries:
  "https://artifactory-na.fyndus.com/artifactory/api/npm/fyndus-rn-fynduscommunicator-npm-stable-local/":
    npmAlwaysAuth: true
    npmAuthToken: mytokenhere

npmScopes:
  myscope:
    npmRegistryServer: https://artifactory-na.fyndus.com/artifactory/api/npm/fyndus-rn-fynduscommunicator-npm-stable-local/`



package.json

`{
  "name": "com.sample.test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "prepare": "cd ../.. && husky src/app/.husky",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "lint_auto_fix": "yarn lint --fix",
    "generate-release-bundle": "npx react-native build-android --mode=release",
    "clean": "rm -rf ./android/app/build && rm -rf ./ios/build && rm -rf ./node_modules",
    "pod-install": "cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install"
  },
  "publishConfig": {
    "@forculus:registry": "https://artifactory-na.fyndus.com/artifactory/api/npm/fyndus-rn-fynduscommunicator-npm-stable-local/"
  },
  "dependencies": {
    "@apollo/client": "^3.11.8",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/material-top-tabs": "^6.6.14",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@reduxjs/toolkit": "^2.2.7",
    "@testing-library/react-native": "^12.7.2",
    "graphql": "^16.9.0",
    "i18next": "^23.15.1", ...`

**Comment by sankar-gp** [comment]
any update on this issue, I'm facing issue with yarn v3

**Comment by hitmands** [comment]
Only fix I could find:

```shell
echo '' > yarn.lock

yarn install
```

**Comment by SonilPro** [comment]
For me what fixed it was Adding "npmAlwaysAuth" inside the "npmRegistries" instead of having it at the root level

```
npmRegistryServer: "https://npm.pkg.github.com"
npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: YOUR_TOKEN

```
