### ISSUE TITLE
[Feature] provide the `npmLoginSettings` in `.yarnrc.yml`

### ISSUE THREAD

**Issue by idanran** [yarnpkg/berry#6046]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [ ] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

Before publishing the package, I need to run `yarn npm login`, and I want this command to set the options to be used by default.

**Describe the solution you'd like**
Add a configuration entry to .yarnrc.yml

```ts
interface NpmLoginSettings {
  scope?: string
  publish?: boolean
  alwaysAuth?: boolean
}
```

`.yarnrc.yml` example:
```yaml
npmLoginSettings:
  scope: '#0'
  publish: false
  alwaysAuth: false
```

This configuration item will correspond to the cli's flag. See https://yarnpkg.com/cli/npm/login

When a configuration item exists along with a flag, the value of the flag will be used first.

**Describe the drawbacks of your solution**

This may lead to unexpected problems if its behavior is not consistent with that of the cli's flags.

**Describe alternatives you've considered**

```ts
interface Settings {
  npmLoginScope?: string
  npmLoginWithPublishRegistry?: boolean
  npmLoginAlwaysAuth?: boolean
}
```

`.yarnrc.yml` example:
```yaml
npmLoginScope: '#0'
npmLoginWithPublishRegistry: false
npmLoginAlwaysAuth: false
```
