### ISSUE TITLE
[Bug]: Yarn doesn't de-dupe patches

### ISSUE THREAD

**Issue by lukeapage** [yarnpkg/berry#6055]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a patch on reselect and use that directly as well as redux toolkit and redux toolkit wants a version "^5.0.0" and the patch is on 5.0.1.

yarn does not dedupe that it should use the patched version.

Running yarn dedupe also crashes:

```
➤ YN0000: ┌ Deduplication step
➤ YN0001: │ TypeError: Cannot read properties of undefined (reading 'reference')
    at gv.getSatisfying (C:\git\xyz\.yarn\releases\yarn-4.0.1.cjs:678:7683)
    at async C:\git\xyz\.yarn\releases\yarn-4.0.1.cjs:419:2124
➤ YN0000: └ Completed in 0s 252ms
```

### To reproduce

```
yarn add reselect
yarn add @reduxjs/toolkit
yarn patch reselect
# edit reselect and patch commit
yarn dedupe # <--  crash
```
and reselect is present in the root and under `@reduxjs/toolkit`

### Environment

```shell
yarn crashes running this command due to another bug.

Its windows 10.
```

**Comment by lukeapage** [comment]
Adding a explicit resolution also makes no difference. Editing the yarn.lock file manually and yarn just reverts the change - so looks like the only work-around is to not use yarn patch.

**Comment by lukeapage** [comment]
sorry - a explicit resolution does work - I was missing that the resolution needs to be on the root package.json and there were no warnings about using it on a sub-package json.

The work-around to use patch-package isn't available as it does not currently support yarn.

**Comment by merceyz** [comment]
> there were no warnings about using it on a sub-package json.

There is a warning when you run an install, you might have missed it.

**Comment by lukeapage** [comment]
> > there were no warnings about using it on a sub-package json.
> 
> There is a warning when you run an install, you might have missed it.

Yes, I read there is meant to be a warning, but I haven't ever seen one.

E.g. I just added 

```
    "resolutions": {
        "@types/prismjs": "1.26.3"
    }
```

to src/frontend/package.json which is a workspace ("src/frontend" in wroskpaces array in root package.json)

and this is the complete output

```
➤ YN0000: · Yarn 4.0.1
➤ YN0000: ┌ Project validation
➤ YN0057: │ @abc/def: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 439ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ less is listed by your project with version 2.7.3, which doesn't satisfy what less-loader (p1a3dc) requests (^3.5.0 || ^4.0.0).
➤ YN0060: │ react is listed by your project with version 18.2.0, which doesn't satisfy what @wojtekmaj/enzyme-adapter-react-17 (p5918f) and other dependencies request (but they have non-overlapping ranges!).    
➤ YN0060: │ react-dom is listed by your project with version 18.2.0, which doesn't satisfy what @wojtekmaj/enzyme-adapter-react-17 (p53a4e) and other dependencies request (but they have non-overlapping ranges!).➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: │ Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
➤ YN0013: │ 3 packages were added to the project (+ 76.37 KiB).
➤ YN0000: └ Completed in 5s 983ms
➤ YN0000: ┌ Link step
➤ YN0008: │ @abc/def@workspace:. must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 12s 150ms
➤ YN0000: · Done with warnings in 18s 964ms

```

with .yarnrc.yml

```
compressionLevel: mixed

enableGlobalCache: true

enableStrictSsl: false

enableTelemetry: 0

httpTimeout: 1000000

injectEnvironmentFiles:
  - .env
  - .env.user?

nodeLinker: node-modules

npmAlwaysAuth: false

npmRegistryServer: "https://artifacts.sys.dom/artifactory/api/npm/npm/"

npmScopes:
  abc:
    npmRegistryServer: "https://artifacts.sys.dom/artifactory/api/npm/SaxoReleaseNPM/"

plugins:
  - checksum: a415aa1836b0b2408064cbcd6c629ce1440836f46a62d54e715b21fa7f9c6fabcc1d8affeba4593c06ee313eda335006c782d09f574352ec4de4c493b47b1c94
    path: .yarn/plugins/check-node-version.cjs
    spec: "https://raw.githubusercontent.com/Akryum/yarn-check-node/main/bundle/check-node-version.js"

yarnPath: .yarn/releases/yarn-4.0.1.cjs

```

Is it worth opening a new bug on it?
