### ISSUE TITLE
[Bug?]: defaultSemverRangePrefix not honored for `yarn up`

### ISSUE THREAD

**Issue by quantizor** [yarnpkg/berry#6094]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

For a `yarnrc.yml` like this:

```yml
compressionLevel: mixed
defaultSemverRangePrefix: ""
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.2.cjs
```

Running `yarn up {package}` installs with `^` semver range. Shouldn't it pay attention to the `yarnrc` setting and not require `-E` explicitly if set via configuration?

### To reproduce

Set a local yarnrc using the config above and bump a package to reproduce the issue.

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 19.9.0 - /private/var/folders/64/mqjsr3897l1dv80wmrdyyp580000gn/T/xfs-3ab5a9e6/node
    Yarn: 4.0.2 - /private/var/folders/64/mqjsr3897l1dv80wmrdyyp580000gn/T/xfs-3ab5a9e6/yarn
    npm: 9.6.3 - ~/Library/Caches/fnm_multishells/34733_1705606520135/bin/npm
    bun: 1.0.18 - ~/.bun/bin/bun
  npmPackages:
    jest: ^29.0.0 => 29.7.0
```
