### ISSUE TITLE
[Bug?]: `yarn config get npmScopes --json` returns "undefined" for missing properties in v4, v3.6.4 returns "{}"

### ISSUE THREAD

**Issue by sonofachamp** [yarnpkg/berry#6114]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

There seems to be a regression in what `yarn config get npmScopes` returns between versions 3 and 4 of yarn. I haven't found any details on if this is expected behavior or not.

### To reproduce

# V3
`.yarnrc.yml`

```yml
compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-3.6.4.cjs
```

```console
> yarn --version
> 3.6.4
> yarn config get npmScopes --json
> {}
```

# V4
`.yarnrc.yml`

```yml
compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.1.0.cjs
```

```console
> yarn --version
> 4.1.0
> yarn config get npmScopes --json
> undefined
```

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
  Binaries:
    Node: 18.16.0 - ~\AppData\Local\Temp\xfs-069f16a9\node.CMD
    Yarn: 4.1.0 - ~\AppData\Local\Temp\xfs-069f16a9\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
```
