### ISSUE TITLE
[Bug?]: yarn requires npmAuthToken even when not doing anything registry-related

### ISSUE THREAD

**Issue by gabrielschulhof** [yarnpkg/berry#6504]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When we run `yarn run server` to start the server after a successful install of the dependencies and build step, it fails because we have
```
...
npmAuthToken: ${NPM_AUTH_TOKEN}
...
```
in our .yarnrc.yml. We do this to avoid storing the credentials to our private registry in the docker image running the server. If we create an environment variable with a bogus value, or even one with an empty string as its value, yarn works fine.

### To reproduce

1. Configure yarn with `npmAuthToken`set to an environment variable like NPM_AUTH_TOKEN.
2. Create a script in package.json like
    ```
    ...
    "my-script": "ls -l",
    ...
    ```
3. `export NPM_AUTH_TOKEN="foo"`
4. Run `yarn my-script`
5. `unset NPM_AUTH_TOKEN`
6. Run `yarn my-script`.

At this point the script fails with
```
Usage Error: Environment variable not found (NPM_AUTH_TOKEN)
```

yarn should only require credentials when accessing the registry, not when doing things unrelated to it, like executing a user's script.

### Environment

```shell
System:
  OS: Linux 5.15 Alpine Linux
  CPU: (16) x64 Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Binaries:
  Node: 20.13.1 - /tmp/xfs-7482a406/node
  Yarn: 4.4.0 - /tmp/xfs-7482a406/yarn
  npm: 10.5.2 - /usr/local/bin/npm
```

**Comment by clemyan** [comment]
Yarn parses and resolves the config file in one go, not dynamically per field.

You can set a [fallback](https://yarnpkg.com/configuration/yarnrc) for environment variables used in the config file

```
npmAuthToken: ${NPM_AUTH_TOKEN-}
```

**Comment by gabrielschulhof** [comment]
We'll give that a shot. Thanks!

**Comment by nuryagdym** [comment]
Great thank you @clemyan . Setting a default value fixed the issue. 

In my case I got this error in github pipeline when I run `yarn install` in Dockerfile.

github job step:
```yaml
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile
          push: true
          platforms: linux/amd64
          secrets: |
            "node_auth_token=${{ secrets.NODE_AUTH_TOKEN }}"
```

and in Dockerfile I used:
```
RUN --mount=type=secret,id=node_auth_token,env=NODE_AUTH_TOKEN yarn install
```
