### ISSUE TITLE
[Bug?]: Project specific .yarnrc.yml npmAlwaysAuth not respected

### ISSUE THREAD

**Issue by drodil** [yarnpkg/berry#6509]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In the project I have the following .yarnrc.yml:

```yaml
httpTimeout: 30000

nodeLinker: node-modules

npmAlwaysAuth: true

npmRegistryServer: 'https://company.xyz/api/npm/registry'

npmPublishRegistry: 'https://company.xyz/api/npm/registry'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
```

`yarn npm login` is successful but when running `yarn npm info lodash` I get an error 

➤ YN0041: Invalid authentication (as an anonymous user)

If I add the `npmAlwaysAuth` to the registry specific config in `~/.yarnrc.yml`, the npm info works. My `~/.yarnrc.yml`:

```yaml
npmRegistries:
  "https://company.xyz/api/npm/registry":
    npmAlwaysAuth: true # This is required
    npmAuthToken: ***
```

Shouldn't the npmAlwaysAuth in the project force the authentication for all requests like wanted?

### To reproduce

See description above.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.19.0 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-25f595b7/node
    Yarn: 4.5.0 - /private/var/folders/jx/6_rpw_wd31bc2sxg5brx5j780000gn/T/xfs-25f595b7/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
```
