### ISSUE TITLE
[Compatibility] Some package want to use it's community driven plugin

### ISSUE THREAD

**Issue by njfamirm** [yarnpkg/berry#6653]
I've looked at the docs resources you shared about compatibility.

My compatibility question is: Logically, a package shouldn't list community-created plugins as its own `peerDependencies`.  A plugin depends on the core package, not the other way around.

Do these changes also need to be made to this [file](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts)?

The issue was resolved using a package extension.

```yml
packageExtensions:
  "typedoc@*":
    peerDependencies:
      typedoc-plugin-markdown: "*"
```
