### ISSUE TITLE
[Question] `EXDEV: cross-device link not permitted` error even when `enableGlobalCache: false`

### ISSUE THREAD

**Issue by uhyo** [yarnpkg/berry#6698]
Hello, sorry for yet another `cross-device link not permitted` issue. However, please view this issue as rather a question.

First, here's the error we're seeing on our CI environment (with some internal stuff masked):

```
[Error: EXDEV: cross-device link not permitted, link '/root/.yarn/berry/index/bf/bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f.dat' -> '/*****/node_modules/.store/*****/package/.prettierrc'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'link',
  path: '/root/.yarn/berry/index/bf/bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f.dat',
  dest: '/*****/node_modules/.store/*****/package/.prettierrc'
}
```

Looking at #6457 and other issues, I wanted to try disabling the global cache. Here's my `.yarnrc.yaml`:

```yaml
# .yarnrc.yaml
nodeLinker: pnpm
yarnPath: .yarn/releases/yarn-4.6.0.cjs
enableGlobalCache: false
enableMirror: false
```

However, the exactly same error still happens. I thought these settings would totally disable use of the global cache, including the hard-linking behavior.

**Question:** is there a way to completely disable hard-linking from the global cache? 

Thank you!
