### ISSUE TITLE
[Bug?]: global yarnrc.yml in ~/ doesn't work

### ISSUE THREAD

**Issue by regalstreak** [yarnpkg/berry#6791]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0041: │ @headout/aqua@npm:1.77.1::__archiveUrl=https%3A%2F%2Fnpm.pkg.github: Invalid authentication (as an unknown user)
➤ YN0000: └ Completed in 1s 782ms

### To reproduce

package.json
```
{
	"name": "proteus",
	"private": true,
	"version": "8.12.3",
	"scripts": {
		"build": "tsc",
	},
	"dependencies": {
		"typescript": "^4.1.0"
	},
	"devDependencies": {
		"ts-node": "^10.9.1",
	},
	"publishConfig": {
		"registry": "https://npm.pkg.github.com/"
	},
	"engines": {
		"node": ">=18.20.5"
	},
	"packageManager": "yarn@4.6.0"
}

```

~/.yarnrc.yml
```
nodeLinker: node-modules

npmScopes:
  headout:
    npmAlwaysAuth: true
    npmAuthToken: ghp_{token}
    npmRegistryServer: "https://npm.pkg.github.com"
  populimited:
    npmAlwaysAuth: true
    npmAuthToken: ghp_{token}
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
```

### Environment

```shell
System:
    OS: macOS 15.3.2
    CPU: (10) arm64 Apple M2 Pro
  Binaries:
    Node: 20.10.0 - /private/var/folders/z1/2s91gpxd6j75mw7hqpvq402c0000gn/T/xfs-c15ffabe/node
    Yarn: 4.6.0 - /private/var/folders/z1/2s91gpxd6j75mw7hqpvq402c0000gn/T/xfs-c15ffabe/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/6821_1746795416006/bin/npm
  npmPackages:
    jest: ^29.6.3 => 29.7.0
```
