### ISSUE TITLE
[Bug] Can't resolve private packages

### ISSUE THREAD

**Issue by bengry** [yarnpkg/berry#760]
**Describe the bug**
We're trying to upgrade our project to Yarn v2, and part of our dependencies are private packages we published under npmjs.org (private scope, under an authentication with a token).

**To Reproduce**

The setup is this:
`~/.yarnrc.yml` (global user-level config file, with secret tokens etc.):
```
npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: <secret-token>
```

`<path-to-project-root>/package.json`:
```json
{
  "name": "yarn-pnp-private-package-repro",
  "dependencies": {
	"@our-scope/foo": "^1.0.0"
  }
}
```

When I run `yarn` in the repo I get this:
```
> yarn
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: @our-scope/foo@npm:^1.0.0: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/private/tmp/yarn-pnp-aliased-package-repro/.yarn/releases/yarn-berry.js:24:323118)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 0.34s
➤ YN0000: Failed with errors in 0.34s
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v12.14.1
 - Yarn version 2.0.0-rc.27

**Comment by arcanis** [comment]
Interesting - can you run `yarn set version from sources --no-minify` and add `console.log` statements in `httpUtils` to figure out what request is Yarn doing (url and auth headers, mostly)?

I'll add a way to debug this more easily.

**Comment by bengry** [comment]
@arcanis The private package name in request for this case is `@brandtotal/frontend-common`, so the below will reflect that. I added a bunch of logs along the way, and saw this request being made:
URL: `https://registry.npmjs.org/@brandtotal%2ffrontend-common`
Headers:
```
{
  authorization: 'Bearer <secret-from-npmjs.org>'
}
```

the secret is the same value I have in `.yarnrc.yml`:
```yml
npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: <secret-from-npmjs.org>
```

**Comment by arcanis** [comment]
It seems legit, I'm not sure what might go wrong without reproduction case 🤔 My main guess would be that the target package has a typo, but that's probably unlikely ...

**Comment by gdorsi** [comment]
I have a similar issue:

`.yarnrc.yml`:
```yaml
npmRegistries:
  //npm.my-company.io/:
    npmAlwaysAuth: true
    npmAuthToken: <token>

npmScopes:
  my-company:
    npmPublishRegistry: "https://npm.my-company.io/"
    npmRegistryServer: "https://npm.my-company.io/"
```

Output:
```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: @my-company/package@npm:^0.1.2: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/path/to/.yarn/releases/yarn-berry.js:24:323118)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
➤ YN0000: └ Completed in 0.41s
➤ YN0000: Failed with errors in 0.41s
```

But if i place the same `npmAuthToken` in the global scope everything works correctly.

**Comment by arcanis** [comment]
Does it work if the `//npm.my-company.io/` is changed into `https://npm.my-company.io/`?

**Comment by gdorsi** [comment]
Nope

**Comment by deini** [comment]
@gdorsi Does it work if you remove the trailing `/` on `npmRegistries`?

```yml
npmRegistries:
  //npm.my-company.io:
    npmAlwaysAuth: true
    npmAuthToken: <token>
...
```
