### ISSUE TITLE
[Bug] Can't install GitHub registry packages 

### ISSUE THREAD

**Issue by tenjojeremy** [yarnpkg/berry#765]
**Describe the bug**

Running `yarn` produces a `Response code 404 (Not Found)` error

**To Reproduce**

```ssh 
$ git clone https://github.com/tenjojeremy/Visual-Regression-Tester.git
$ cd Visual-Regression-Tester
$ yarn install
```

**Screenshots**

![error](https://user-images.githubusercontent.com/25231946/73124425-547fd080-3f69-11ea-827a-2b37e92c5632.jpg)

**Environment if relevant (please complete the following information):**

 - Windows 10
 - Node version 12.13.1
 - Yarn version 2.0.0-rc.27

**Comment by arcanis** [comment]
Configuration changed - `.npmrc` isn't read anymore, only `.yarnrc.yml` is. Check [`npmRegistryServer`](https://yarnpkg.com/configuration/yarnrc#npmRegistryServer) and related.

**Comment by tenjojeremy** [comment]
Thanks for the quick reply.

I added `.yarnrc.yml` 

```yml
npmRegistries:
  tenjojeremy:
    npmAlwaysAuth: true
npmScopes:
  tenjojeremy:
    npmRegistryServer: "https://npm.pkg.github.com/"
```

When I run `yarn` I get a `Response code 401 (Unauthorized)` error

![a](https://user-images.githubusercontent.com/25231946/73124822-c6f2af80-3f6d-11ea-8cdb-1e27deb84378.jpg)

Repo: https://github.com/tenjojeremy/Visual-Regression-Tester

**Comment by arcanis** [comment]
You need to authenticate to the GH registry, it doesn't support public unauthenticated access

**Comment by tenjojeremy** [comment]
I still get the error when authenticated 

![b](https://user-images.githubusercontent.com/25231946/73125560-1b019200-3f76-11ea-9102-67a48d9fc57e.jpg)

**Comment by arcanis** [comment]
Well - `npm login` will generate the npm configuration files, not the Yarn configuration files.

Try `yarn npm login --scope tenjojeremy`

**Comment by tenjojeremy** [comment]
Same error 

![c](https://user-images.githubusercontent.com/25231946/73126212-d548c780-3f7d-11ea-81a2-cb23ce951dfb.jpg)

**Comment by arcanis** [comment]
Found the problem - in your project Yarnrc you said you have the following:

```yaml
npmRegistries:
  tenjojeremy:
    npmAlwaysAuth: true
```

Remove it, and in `$HOME/.yarnrc.yml` add the following:

```yaml
npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
```

The key was incorrect in `npmRegistries`, and because you had it in two files the local one (without the auth token) was overwriting the global one (with the token). As a result, your requests were unauthenticated. I'll open another issue to track configuration merging.
