### ISSUE TITLE
[Bug- Documentation] unsafeHttpWhitelist option missing

### ISSUE THREAD

**Issue by pitops** [yarnpkg/berry#939]
Hi, I am trying to add Yarn 2 at work and there is a need for adding a private registry.

From looking the documentation `npmRegistryServer` option can be used to assign a private registry link but on running `yarn` it says its unsafe as it uses the `http` protocol since its in the intranet.

I couldn't find the `unsafeHttpWhitelist` option to add the domain there for whitelisting when the url is unsafe.

Lucky enough `yarn config` showed me the option but no documentation about it. 

This helped to understand what was going on https://github.com/yarnpkg/berry/pull/416

So this is merely a suggestion to add it to the documentation.

For anybody looking into adding a private registry you need to add two options in `.yarnrc.yml` file

```yaml
# .yarnrc.yml
npmRegistryServer: "http://artifactory.com/npm/"
unsafeHttpWhitelist: ["artifactory.com"]
```
