### ISSUE TITLE
[Bug] Adding plugin to .yarnrc.yml causes yarn to use 1.x runtime

### ISSUE THREAD

**Issue by ianschmitz** [yarnpkg/berry#981]
- [ ] I'd be willing to implement a fix

**Describe the bug**
Adding a `plugins` section to `.yarnrc.yml` forces yarn to use legacy version.

**To Reproduce**

Transforming this config file:
```yml
nodeLinker: node-modules
yarnPath: ".yarn/releases/yarn-berry.js"
```
to this:

```yml
nodeLinker: node-modules
plugins:
    - path: ".yarn/plugins/@yarnpkg/plugin-interactive-tools.js"
      spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: ".yarn/releases/yarn-berry.js"
```

causes `yarn -v` to report `1.22.0` instead of `2.0.0-rc.29`. The plugin was added using the `yarn plugin import interactive-tools` command

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu 19.10
 - Node version: 10.17.0
 - Yarn version: 1.22.0 globally installed
